//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票超限量发票种类自定义VO
 * 
 * <p>Java class for FpCxlFpzlVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FpCxlFpzlVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="myzggpsl" type="{http://www.chinatax.gov.cn/dataspec/}fpsl"/>
 *         &lt;element name="dyykfpje" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FpCxlFpzlVO", propOrder = {
    "fpzlDm",
    "myzggpsl",
    "dyykfpje"
})
public class FpCxlFpzlVO {

    @XmlElement(required = true)
    protected String fpzlDm;
    protected double myzggpsl;
    protected double dyykfpje;

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the myzggpsl property.
     * 
     */
    public double getMyzggpsl() {
        return myzggpsl;
    }

    /**
     * Sets the value of the myzggpsl property.
     * 
     */
    public void setMyzggpsl(double value) {
        this.myzggpsl = value;
    }

    /**
     * Gets the value of the dyykfpje property.
     * 
     */
    public double getDyykfpje() {
        return dyykfpje;
    }

    /**
     * Sets the value of the dyykfpje property.
     * 
     */
    public void setDyykfpje(double value) {
        this.dyykfpje = value;
    }

}
