//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 真伪鉴定结果通知书VO
 * 
 * <p>Java class for FpzwjdmxjgVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FpzwjdmxjgVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh"/>
 *         &lt;element name="nsrmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="kjrq" type="{http://www.chinatax.gov.cn/dataspec/}lrrq"/>
 *         &lt;element name="fpzlmc" type="{http://www.chinatax.gov.cn/dataspec/}fpzlmc"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="fpqshm" type="{http://www.chinatax.gov.cn/dataspec/}fpqshm"/>
 *         &lt;element name="fpzzhm" type="{http://www.chinatax.gov.cn/dataspec/}fpzzhm"/>
 *         &lt;element name="fpfs" type="{http://www.chinatax.gov.cn/dataspec/}sl"/>
 *         &lt;element name="kpje" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="fpjdjgmc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FpzwjdmxjgVO", propOrder = {
    "nsrsbh",
    "nsrmc",
    "kjrq",
    "fpzlmc",
    "fpDm",
    "fpqshm",
    "fpzzhm",
    "fpfs",
    "kpje",
    "fpjdjgmc"
})
public class FpzwjdmxjgVO {

    @XmlElement(required = true)
    protected String nsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String nsrmc;
    @XmlElement(required = true, nillable = true)
    protected String kjrq;
    @XmlElement(required = true, nillable = true)
    protected String fpzlmc;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true, nillable = true)
    protected String fpqshm;
    @XmlElement(required = true, nillable = true)
    protected String fpzzhm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double fpfs;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double kpje;
    @XmlElement(required = true, nillable = true)
    protected String fpjdjgmc;

    /**
     * Gets the value of the nsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsrsbh() {
        return nsrsbh;
    }

    /**
     * Sets the value of the nsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsrsbh(String value) {
        this.nsrsbh = value;
    }

    /**
     * Gets the value of the nsrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsrmc() {
        return nsrmc;
    }

    /**
     * Sets the value of the nsrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsrmc(String value) {
        this.nsrmc = value;
    }

    /**
     * Gets the value of the kjrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKjrq() {
        return kjrq;
    }

    /**
     * Sets the value of the kjrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKjrq(String value) {
        this.kjrq = value;
    }

    /**
     * Gets the value of the fpzlmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlmc() {
        return fpzlmc;
    }

    /**
     * Sets the value of the fpzlmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlmc(String value) {
        this.fpzlmc = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the fpqshm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpqshm() {
        return fpqshm;
    }

    /**
     * Sets the value of the fpqshm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpqshm(String value) {
        this.fpqshm = value;
    }

    /**
     * Gets the value of the fpzzhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzzhm() {
        return fpzzhm;
    }

    /**
     * Sets the value of the fpzzhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzzhm(String value) {
        this.fpzzhm = value;
    }

    /**
     * Gets the value of the fpfs property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFpfs() {
        return fpfs;
    }

    /**
     * Sets the value of the fpfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFpfs(Double value) {
        this.fpfs = value;
    }

    /**
     * Gets the value of the kpje property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getKpje() {
        return kpje;
    }

    /**
     * Sets the value of the kpje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKpje(Double value) {
        this.kpje = value;
    }

    /**
     * Gets the value of the fpjdjgmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpjdjgmc() {
        return fpjdjgmc;
    }

    /**
     * Sets the value of the fpjdjgmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpjdjgmc(String value) {
        this.fpjdjgmc = value;
    }

}
