//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 œ¬ŒÁ CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * ∑¢∆±π“ ßÀªŸ…Í«Î±®∏ÊVO
 * 
 * <p>Java class for FPGsshsqbgVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPGsshsqbgVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="gssm" type="{http://www.chinatax.gov.cn/dataspec/}gssm"/>
 *         &lt;element name="skqj" type="{http://www.chinatax.gov.cn/dataspec/}skqj"/>
 *         &lt;element name="sfwfwz" type="{http://www.chinatax.gov.cn/dataspec/}sfwfwz"/>
 *         &lt;element name="sqrxm" type="{http://www.chinatax.gov.cn/dataspec/}sqrxm"/>
 *         &lt;element name="wfwzcyDm" type="{http://www.chinatax.gov.cn/dataspec/}wfwzcyDm"/>
 *         &lt;element name="sqrq" type="{http://www.chinatax.gov.cn/dataspec/}sqrq"/>
 *         &lt;element name="gssquuid" type="{http://www.chinatax.gov.cn/dataspec/}gssquuid"/>
 *         &lt;element name="wfwzsdDm" type="{http://www.chinatax.gov.cn/dataspec/}wfwzsdDm"/>
 *         &lt;element name="wfwzlxDm" type="{http://www.chinatax.gov.cn/dataspec/}wfwzlxDm"/>
 *         &lt;element name="slswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}slswjgDm"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="gsshqksm" type="{http://www.chinatax.gov.cn/dataspec/}gsshqksm"/>
 *         &lt;element name="wfwzjl" type="{http://www.chinatax.gov.cn/dataspec/}wfwzjl"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="slrq" type="{http://www.chinatax.gov.cn/dataspec/}slrq"/>
 *         &lt;element name="slrDm" type="{http://www.chinatax.gov.cn/dataspec/}slrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPGsshsqbgVO", propOrder = {
    "sjgsdq",
    "djxh",
    "gssm",
    "skqj",
    "sfwfwz",
    "sqrxm",
    "wfwzcyDm",
    "sqrq",
    "gssquuid",
    "wfwzsdDm",
    "wfwzlxDm",
    "slswjgDm",
    "lrrDm",
    "gsshqksm",
    "wfwzjl",
    "xgrDm",
    "slrq",
    "slrDm"
})
@XmlSeeAlso({
    FPGsshsqbgMxJcVO.class
})
public class FPGsshsqbgVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String gssm;
    @XmlElement(required = true, nillable = true)
    protected String skqj;
    @XmlElement(required = true, nillable = true)
    protected String sfwfwz;
    @XmlElement(required = true, nillable = true)
    protected String sqrxm;
    @XmlElement(required = true, nillable = true)
    protected String wfwzcyDm;
    @XmlElement(required = true, nillable = true)
    protected String sqrq;
    @XmlElement(required = true, nillable = true)
    protected String gssquuid;
    @XmlElement(required = true, nillable = true)
    protected String wfwzsdDm;
    @XmlElement(required = true, nillable = true)
    protected String wfwzlxDm;
    @XmlElement(required = true, nillable = true)
    protected String slswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String gsshqksm;
    @XmlElement(required = true, nillable = true)
    protected String wfwzjl;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String slrq;
    @XmlElement(required = true, nillable = true)
    protected String slrDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the gssm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGssm() {
        return gssm;
    }

    /**
     * Sets the value of the gssm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGssm(String value) {
        this.gssm = value;
    }

    /**
     * Gets the value of the skqj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkqj() {
        return skqj;
    }

    /**
     * Sets the value of the skqj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkqj(String value) {
        this.skqj = value;
    }

    /**
     * Gets the value of the sfwfwz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSfwfwz() {
        return sfwfwz;
    }

    /**
     * Sets the value of the sfwfwz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSfwfwz(String value) {
        this.sfwfwz = value;
    }

    /**
     * Gets the value of the sqrxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqrxm() {
        return sqrxm;
    }

    /**
     * Sets the value of the sqrxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqrxm(String value) {
        this.sqrxm = value;
    }

    /**
     * Gets the value of the wfwzcyDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfwzcyDm() {
        return wfwzcyDm;
    }

    /**
     * Sets the value of the wfwzcyDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfwzcyDm(String value) {
        this.wfwzcyDm = value;
    }

    /**
     * Gets the value of the sqrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqrq() {
        return sqrq;
    }

    /**
     * Sets the value of the sqrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqrq(String value) {
        this.sqrq = value;
    }

    /**
     * Gets the value of the gssquuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGssquuid() {
        return gssquuid;
    }

    /**
     * Sets the value of the gssquuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGssquuid(String value) {
        this.gssquuid = value;
    }

    /**
     * Gets the value of the wfwzsdDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfwzsdDm() {
        return wfwzsdDm;
    }

    /**
     * Sets the value of the wfwzsdDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfwzsdDm(String value) {
        this.wfwzsdDm = value;
    }

    /**
     * Gets the value of the wfwzlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfwzlxDm() {
        return wfwzlxDm;
    }

    /**
     * Sets the value of the wfwzlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfwzlxDm(String value) {
        this.wfwzlxDm = value;
    }

    /**
     * Gets the value of the slswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlswjgDm() {
        return slswjgDm;
    }

    /**
     * Sets the value of the slswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlswjgDm(String value) {
        this.slswjgDm = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the gsshqksm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsshqksm() {
        return gsshqksm;
    }

    /**
     * Sets the value of the gsshqksm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsshqksm(String value) {
        this.gsshqksm = value;
    }

    /**
     * Gets the value of the wfwzjl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfwzjl() {
        return wfwzjl;
    }

    /**
     * Sets the value of the wfwzjl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfwzjl(String value) {
        this.wfwzjl = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the slrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrq() {
        return slrq;
    }

    /**
     * Sets the value of the slrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrq(String value) {
        this.slrq = value;
    }

    /**
     * Gets the value of the slrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrDm() {
        return slrDm;
    }

    /**
     * Sets the value of the slrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrDm(String value) {
        this.slrDm = value;
    }

}
