//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票领购簿发放VO
 * 
 * <p>Java class for FPLgbffVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPLgbffVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fpglyxm" type="{http://www.chinatax.gov.cn/dataspec/}fpglyxm"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="sfzjlxDm" type="{http://www.chinatax.gov.cn/dataspec/}sfzjlxDm"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="wszzrq" type="{http://www.chinatax.gov.cn/dataspec/}wszzrq"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="slswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}slswjgDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="fplgbuuid" type="{http://www.chinatax.gov.cn/dataspec/}fplgbuuid"/>
 *         &lt;element name="sfzjhm" type="{http://www.chinatax.gov.cn/dataspec/}sfzjhm"/>
 *         &lt;element name="fplgbhm" type="{http://www.chinatax.gov.cn/dataspec/}fplgbhm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPLgbffVO", propOrder = {
    "sjgsdq",
    "fpglyxm",
    "djxh",
    "sfzjlxDm",
    "lcslid",
    "wszzrq",
    "lrrDm",
    "slswjgDm",
    "xgrDm",
    "fplgbuuid",
    "sfzjhm",
    "fplgbhm"
})
public class FPLgbffVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fpglyxm;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String sfzjlxDm;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String wszzrq;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String slswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String fplgbuuid;
    @XmlElement(required = true, nillable = true)
    protected String sfzjhm;
    @XmlElement(required = true, nillable = true)
    protected String fplgbhm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fpglyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpglyxm() {
        return fpglyxm;
    }

    /**
     * Sets the value of the fpglyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpglyxm(String value) {
        this.fpglyxm = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the sfzjlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSfzjlxDm() {
        return sfzjlxDm;
    }

    /**
     * Sets the value of the sfzjlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSfzjlxDm(String value) {
        this.sfzjlxDm = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the wszzrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWszzrq() {
        return wszzrq;
    }

    /**
     * Sets the value of the wszzrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWszzrq(String value) {
        this.wszzrq = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the slswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlswjgDm() {
        return slswjgDm;
    }

    /**
     * Sets the value of the slswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlswjgDm(String value) {
        this.slswjgDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the fplgbuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFplgbuuid() {
        return fplgbuuid;
    }

    /**
     * Sets the value of the fplgbuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFplgbuuid(String value) {
        this.fplgbuuid = value;
    }

    /**
     * Gets the value of the sfzjhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSfzjhm() {
        return sfzjhm;
    }

    /**
     * Sets the value of the sfzjhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSfzjhm(String value) {
        this.sfzjhm = value;
    }

    /**
     * Gets the value of the fplgbhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFplgbhm() {
        return fplgbhm;
    }

    /**
     * Sets the value of the fplgbhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFplgbhm(String value) {
        this.fplgbhm = value;
    }

}
