//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务行政许可变动情况申请审批表VO
 * 
 * <p>Java class for FPSwxzxkBdqkSqspVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwxzxkBdqkSqspVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="bdswxzxkuuid" type="{http://www.chinatax.gov.cn/dataspec/}bdswxzxkuuid"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="zstybz" type="{http://www.chinatax.gov.cn/dataspec/}zstybz"/>
 *         &lt;element name="slswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}slswjgDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="bdswxzxklxDm" type="{http://www.chinatax.gov.cn/dataspec/}bdswxzxklxDm"/>
 *         &lt;element name="zsrq3" type="{http://www.chinatax.gov.cn/dataspec/}zsrq3"/>
 *         &lt;element name="zsrDm" type="{http://www.chinatax.gov.cn/dataspec/}zsrDm"/>
 *         &lt;element name="slrq" type="{http://www.chinatax.gov.cn/dataspec/}slrq"/>
 *         &lt;element name="slrDm" type="{http://www.chinatax.gov.cn/dataspec/}slrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwxzxkBdqkSqspVO", propOrder = {
    "sjgsdq",
    "djxh",
    "bdswxzxkuuid",
    "lcslid",
    "lrrDm",
    "zstybz",
    "slswjgDm",
    "xgrDm",
    "bdswxzxklxDm",
    "zsrq3",
    "zsrDm",
    "slrq",
    "slrDm"
})
public class FPSwxzxkBdqkSqspVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String bdswxzxkuuid;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String zstybz;
    @XmlElement(required = true, nillable = true)
    protected String slswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String bdswxzxklxDm;
    @XmlElement(required = true, nillable = true)
    protected String zsrq3;
    @XmlElement(required = true, nillable = true)
    protected String zsrDm;
    @XmlElement(required = true, nillable = true)
    protected String slrq;
    @XmlElement(required = true, nillable = true)
    protected String slrDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the bdswxzxkuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBdswxzxkuuid() {
        return bdswxzxkuuid;
    }

    /**
     * Sets the value of the bdswxzxkuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBdswxzxkuuid(String value) {
        this.bdswxzxkuuid = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the zstybz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZstybz() {
        return zstybz;
    }

    /**
     * Sets the value of the zstybz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZstybz(String value) {
        this.zstybz = value;
    }

    /**
     * Gets the value of the slswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlswjgDm() {
        return slswjgDm;
    }

    /**
     * Sets the value of the slswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlswjgDm(String value) {
        this.slswjgDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the bdswxzxklxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBdswxzxklxDm() {
        return bdswxzxklxDm;
    }

    /**
     * Sets the value of the bdswxzxklxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBdswxzxklxDm(String value) {
        this.bdswxzxklxDm = value;
    }

    /**
     * Gets the value of the zsrq3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZsrq3() {
        return zsrq3;
    }

    /**
     * Sets the value of the zsrq3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZsrq3(String value) {
        this.zsrq3 = value;
    }

    /**
     * Gets the value of the zsrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZsrDm() {
        return zsrDm;
    }

    /**
     * Sets the value of the zsrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZsrDm(String value) {
        this.zsrDm = value;
    }

    /**
     * Gets the value of the slrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrq() {
        return slrq;
    }

    /**
     * Sets the value of the slrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrq(String value) {
        this.slrq = value;
    }

    /**
     * Gets the value of the slrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrDm() {
        return slrDm;
    }

    /**
     * Sets the value of the slrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrDm(String value) {
        this.slrDm = value;
    }

}
