//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票票种核定初始化VO
 * 
 * <p>Java class for FPFpPzhdCSHVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPFpPzhdCSHVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="djNsrxxVO" type="{http://www.chinatax.gov.cn/dataspec/}DJNsrxxVO"/>
 *         &lt;element name="isPzDffpzgkpxeQj" type="{http://www.chinatax.gov.cn/dataspec/}xybz"/>
 *         &lt;element name="dffpzgkpxejkz" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="fpPzhdxxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="fpPzhdxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdxxVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fpPzhdgprxxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="fpPzhdgprxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdgprxxVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fpPzhdxxLjgpjeVO" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdxxLjgpjeVO"/>
 *         &lt;element name="nsrzgxxVo" type="{http://www.chinatax.gov.cn/dataspec/}NsrzgxxVO"/>
 *         &lt;element name="isJkDefpljgpje" type="{http://www.chinatax.gov.cn/dataspec/}yxbz"/>
 *         &lt;element name="fpPzhdFpzlGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="fpPzhdFpzlGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdFpzlVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dqdensrbz" type="{http://www.chinatax.gov.cn/dataspec/}xybz"/>
 *         &lt;element name="fpPzhdsqspVO" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdsqspVO"/>
 *         &lt;element name="fpPzhdsqspMxGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="fpPzhdsqspMxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdsqspMxVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fpPzhdSqspGprGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fpPzhdSqspGprGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdsqspGprVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPFpPzhdCSHVO", propOrder = {
    "djNsrxxVO",
    "isPzDffpzgkpxeQj",
    "dffpzgkpxejkz",
    "fpPzhdxxGrid",
    "fpPzhdgprxxGrid",
    "fpPzhdxxLjgpjeVO",
    "nsrzgxxVo",
    "isJkDefpljgpje",
    "fpPzhdFpzlGrid",
    "dqdensrbz",
    "fpPzhdsqspVO",
    "fpPzhdsqspMxGrid",
    "fpPzhdSqspGprGrid"
})
public class FPFpPzhdCSHVO {

    @XmlElement(required = true)
    protected DJNsrxxVO djNsrxxVO;
    @XmlElement(required = true)
    protected String isPzDffpzgkpxeQj;
    @XmlElement(required = true)
    protected Object dffpzgkpxejkz;
    @XmlElement(required = true)
    protected FPFpPzhdCSHVO.FpPzhdxxGrid fpPzhdxxGrid;
    @XmlElement(required = true)
    protected FPFpPzhdCSHVO.FpPzhdgprxxGrid fpPzhdgprxxGrid;
    @XmlElement(required = true)
    protected FPPzhdxxLjgpjeVO fpPzhdxxLjgpjeVO;
    @XmlElement(required = true)
    protected NsrzgxxVO nsrzgxxVo;
    @XmlElement(required = true)
    protected String isJkDefpljgpje;
    @XmlElement(required = true)
    protected FPFpPzhdCSHVO.FpPzhdFpzlGrid fpPzhdFpzlGrid;
    @XmlElement(required = true)
    protected String dqdensrbz;
    @XmlElement(required = true)
    protected FPPzhdsqspVO fpPzhdsqspVO;
    @XmlElement(required = true)
    protected FPFpPzhdCSHVO.FpPzhdsqspMxGrid fpPzhdsqspMxGrid;
    @XmlElement(required = true)
    protected FPFpPzhdCSHVO.FpPzhdSqspGprGrid fpPzhdSqspGprGrid;

    /**
     * Gets the value of the djNsrxxVO property.
     * 
     * @return
     *     possible object is
     *     {@link DJNsrxxVO }
     *     
     */
    public DJNsrxxVO getDjNsrxxVO() {
        return djNsrxxVO;
    }

    /**
     * Sets the value of the djNsrxxVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link DJNsrxxVO }
     *     
     */
    public void setDjNsrxxVO(DJNsrxxVO value) {
        this.djNsrxxVO = value;
    }

    /**
     * Gets the value of the isPzDffpzgkpxeQj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPzDffpzgkpxeQj() {
        return isPzDffpzgkpxeQj;
    }

    /**
     * Sets the value of the isPzDffpzgkpxeQj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPzDffpzgkpxeQj(String value) {
        this.isPzDffpzgkpxeQj = value;
    }

    /**
     * Gets the value of the dffpzgkpxejkz property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDffpzgkpxejkz() {
        return dffpzgkpxejkz;
    }

    /**
     * Sets the value of the dffpzgkpxejkz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDffpzgkpxejkz(Object value) {
        this.dffpzgkpxejkz = value;
    }

    /**
     * Gets the value of the fpPzhdxxGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPFpPzhdCSHVO.FpPzhdxxGrid }
     *     
     */
    public FPFpPzhdCSHVO.FpPzhdxxGrid getFpPzhdxxGrid() {
        return fpPzhdxxGrid;
    }

    /**
     * Sets the value of the fpPzhdxxGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPFpPzhdCSHVO.FpPzhdxxGrid }
     *     
     */
    public void setFpPzhdxxGrid(FPFpPzhdCSHVO.FpPzhdxxGrid value) {
        this.fpPzhdxxGrid = value;
    }

    /**
     * Gets the value of the fpPzhdgprxxGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPFpPzhdCSHVO.FpPzhdgprxxGrid }
     *     
     */
    public FPFpPzhdCSHVO.FpPzhdgprxxGrid getFpPzhdgprxxGrid() {
        return fpPzhdgprxxGrid;
    }

    /**
     * Sets the value of the fpPzhdgprxxGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPFpPzhdCSHVO.FpPzhdgprxxGrid }
     *     
     */
    public void setFpPzhdgprxxGrid(FPFpPzhdCSHVO.FpPzhdgprxxGrid value) {
        this.fpPzhdgprxxGrid = value;
    }

    /**
     * Gets the value of the fpPzhdxxLjgpjeVO property.
     * 
     * @return
     *     possible object is
     *     {@link FPPzhdxxLjgpjeVO }
     *     
     */
    public FPPzhdxxLjgpjeVO getFpPzhdxxLjgpjeVO() {
        return fpPzhdxxLjgpjeVO;
    }

    /**
     * Sets the value of the fpPzhdxxLjgpjeVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPPzhdxxLjgpjeVO }
     *     
     */
    public void setFpPzhdxxLjgpjeVO(FPPzhdxxLjgpjeVO value) {
        this.fpPzhdxxLjgpjeVO = value;
    }

    /**
     * Gets the value of the nsrzgxxVo property.
     * 
     * @return
     *     possible object is
     *     {@link NsrzgxxVO }
     *     
     */
    public NsrzgxxVO getNsrzgxxVo() {
        return nsrzgxxVo;
    }

    /**
     * Sets the value of the nsrzgxxVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NsrzgxxVO }
     *     
     */
    public void setNsrzgxxVo(NsrzgxxVO value) {
        this.nsrzgxxVo = value;
    }

    /**
     * Gets the value of the isJkDefpljgpje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsJkDefpljgpje() {
        return isJkDefpljgpje;
    }

    /**
     * Sets the value of the isJkDefpljgpje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsJkDefpljgpje(String value) {
        this.isJkDefpljgpje = value;
    }

    /**
     * Gets the value of the fpPzhdFpzlGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPFpPzhdCSHVO.FpPzhdFpzlGrid }
     *     
     */
    public FPFpPzhdCSHVO.FpPzhdFpzlGrid getFpPzhdFpzlGrid() {
        return fpPzhdFpzlGrid;
    }

    /**
     * Sets the value of the fpPzhdFpzlGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPFpPzhdCSHVO.FpPzhdFpzlGrid }
     *     
     */
    public void setFpPzhdFpzlGrid(FPFpPzhdCSHVO.FpPzhdFpzlGrid value) {
        this.fpPzhdFpzlGrid = value;
    }

    /**
     * Gets the value of the dqdensrbz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDqdensrbz() {
        return dqdensrbz;
    }

    /**
     * Sets the value of the dqdensrbz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDqdensrbz(String value) {
        this.dqdensrbz = value;
    }

    /**
     * Gets the value of the fpPzhdsqspVO property.
     * 
     * @return
     *     possible object is
     *     {@link FPPzhdsqspVO }
     *     
     */
    public FPPzhdsqspVO getFpPzhdsqspVO() {
        return fpPzhdsqspVO;
    }

    /**
     * Sets the value of the fpPzhdsqspVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPPzhdsqspVO }
     *     
     */
    public void setFpPzhdsqspVO(FPPzhdsqspVO value) {
        this.fpPzhdsqspVO = value;
    }

    /**
     * Gets the value of the fpPzhdsqspMxGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPFpPzhdCSHVO.FpPzhdsqspMxGrid }
     *     
     */
    public FPFpPzhdCSHVO.FpPzhdsqspMxGrid getFpPzhdsqspMxGrid() {
        return fpPzhdsqspMxGrid;
    }

    /**
     * Sets the value of the fpPzhdsqspMxGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPFpPzhdCSHVO.FpPzhdsqspMxGrid }
     *     
     */
    public void setFpPzhdsqspMxGrid(FPFpPzhdCSHVO.FpPzhdsqspMxGrid value) {
        this.fpPzhdsqspMxGrid = value;
    }

    /**
     * Gets the value of the fpPzhdSqspGprGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPFpPzhdCSHVO.FpPzhdSqspGprGrid }
     *     
     */
    public FPFpPzhdCSHVO.FpPzhdSqspGprGrid getFpPzhdSqspGprGrid() {
        return fpPzhdSqspGprGrid;
    }

    /**
     * Sets the value of the fpPzhdSqspGprGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPFpPzhdCSHVO.FpPzhdSqspGprGrid }
     *     
     */
    public void setFpPzhdSqspGprGrid(FPFpPzhdCSHVO.FpPzhdSqspGprGrid value) {
        this.fpPzhdSqspGprGrid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="fpPzhdFpzlGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdFpzlVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpPzhdFpzlGridlb"
    })
    public static class FpPzhdFpzlGrid {

        @XmlElement(required = true)
        protected List<FPPzhdFpzlVO> fpPzhdFpzlGridlb;

        /**
         * Gets the value of the fpPzhdFpzlGridlb property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fpPzhdFpzlGridlb property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFpPzhdFpzlGridlb().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FPPzhdFpzlVO }
         * 
         * 
         */
        public List<FPPzhdFpzlVO> getFpPzhdFpzlGridlb() {
            if (fpPzhdFpzlGridlb == null) {
                fpPzhdFpzlGridlb = new ArrayList<FPPzhdFpzlVO>();
            }
            return this.fpPzhdFpzlGridlb;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fpPzhdSqspGprGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdsqspGprVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpPzhdSqspGprGridlb"
    })
    public static class FpPzhdSqspGprGrid {

        @XmlElement(required = true)
        protected FPPzhdsqspGprVO fpPzhdSqspGprGridlb;

        /**
         * Gets the value of the fpPzhdSqspGprGridlb property.
         * 
         * @return
         *     possible object is
         *     {@link FPPzhdsqspGprVO }
         *     
         */
        public FPPzhdsqspGprVO getFpPzhdSqspGprGridlb() {
            return fpPzhdSqspGprGridlb;
        }

        /**
         * Sets the value of the fpPzhdSqspGprGridlb property.
         * 
         * @param value
         *     allowed object is
         *     {@link FPPzhdsqspGprVO }
         *     
         */
        public void setFpPzhdSqspGprGridlb(FPPzhdsqspGprVO value) {
            this.fpPzhdSqspGprGridlb = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="fpPzhdgprxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdgprxxVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpPzhdgprxxGridlb"
    })
    public static class FpPzhdgprxxGrid {

        @XmlElement(required = true)
        protected List<FPPzhdgprxxVO> fpPzhdgprxxGridlb;

        /**
         * Gets the value of the fpPzhdgprxxGridlb property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fpPzhdgprxxGridlb property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFpPzhdgprxxGridlb().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FPPzhdgprxxVO }
         * 
         * 
         */
        public List<FPPzhdgprxxVO> getFpPzhdgprxxGridlb() {
            if (fpPzhdgprxxGridlb == null) {
                fpPzhdgprxxGridlb = new ArrayList<FPPzhdgprxxVO>();
            }
            return this.fpPzhdgprxxGridlb;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="fpPzhdsqspMxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdsqspMxVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpPzhdsqspMxGridlb"
    })
    public static class FpPzhdsqspMxGrid {

        @XmlElement(required = true)
        protected List<FPPzhdsqspMxVO> fpPzhdsqspMxGridlb;

        /**
         * Gets the value of the fpPzhdsqspMxGridlb property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fpPzhdsqspMxGridlb property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFpPzhdsqspMxGridlb().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FPPzhdsqspMxVO }
         * 
         * 
         */
        public List<FPPzhdsqspMxVO> getFpPzhdsqspMxGridlb() {
            if (fpPzhdsqspMxGridlb == null) {
                fpPzhdsqspMxGridlb = new ArrayList<FPPzhdsqspMxVO>();
            }
            return this.fpPzhdsqspMxGridlb;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="fpPzhdxxGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPPzhdxxVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpPzhdxxGridlb"
    })
    public static class FpPzhdxxGrid {

        @XmlElement(required = true)
        protected List<FPPzhdxxVO> fpPzhdxxGridlb;

        /**
         * Gets the value of the fpPzhdxxGridlb property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fpPzhdxxGridlb property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFpPzhdxxGridlb().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FPPzhdxxVO }
         * 
         * 
         */
        public List<FPPzhdxxVO> getFpPzhdxxGridlb() {
            if (fpPzhdxxGridlb == null) {
                fpPzhdxxGridlb = new ArrayList<FPPzhdxxVO>();
            }
            return this.fpPzhdxxGridlb;
        }

    }

}
