//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 二手车销售统一发票存根联采集VO
 * 
 * <p>Java class for FPCglcjEscfpVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPCglcjEscfpVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fphm" type="{http://www.chinatax.gov.cn/dataspec/}fphm"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="fpkjqkDm" type="{http://www.chinatax.gov.cn/dataspec/}fpkjqkDm"/>
 *         &lt;element name="mfmc" type="{http://www.chinatax.gov.cn/dataspec/}mfmc"/>
 *         &lt;element name="mfsfsbh" type="{http://www.chinatax.gov.cn/dataspec/}mfsfsbh"/>
 *         &lt;element name="kprq" type="{http://www.chinatax.gov.cn/dataspec/}kprq"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="cjhj" type="{http://www.chinatax.gov.cn/dataspec/}cjhj"/>
 *         &lt;element name="mfmc1" type="{http://www.chinatax.gov.cn/dataspec/}mfmc1"/>
 *         &lt;element name="esccgluuid" type="{http://www.chinatax.gov.cn/dataspec/}esccgluuid"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="mfsfsbh1" type="{http://www.chinatax.gov.cn/dataspec/}mfsfsbh1"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="cglcjfpyjuuid" type="{http://www.chinatax.gov.cn/dataspec/}cglcjfpyjuuid"/>
 *         &lt;element name="fpcglcjuuid" type="{http://www.chinatax.gov.cn/dataspec/}fpcglcjuuid"/>
 *         &lt;element name="phcd" type="{http://www.chinatax.gov.cn/dataspec/}phcd"/>
 *         &lt;element name="cglsjcjlxDm" type="{http://www.chinatax.gov.cn/dataspec/}cglsjcjlxDm"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPCglcjEscfpVO", propOrder = {
    "sjgsdq",
    "fphm",
    "djxh",
    "fpkjqkDm",
    "mfmc",
    "mfsfsbh",
    "kprq",
    "fpDm",
    "fpzlDm",
    "cjhj",
    "mfmc1",
    "esccgluuid",
    "lrrDm",
    "mfsfsbh1",
    "xgrDm",
    "cglcjfpyjuuid",
    "fpcglcjuuid",
    "phcd",
    "cglsjcjlxDm",
    "zfbz1"
})
public class FPCglcjEscfpVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fphm;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String fpkjqkDm;
    @XmlElement(required = true, nillable = true)
    protected String mfmc;
    @XmlElement(required = true, nillable = true)
    protected String mfsfsbh;
    @XmlElement(required = true, nillable = true)
    protected String kprq;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true)
    protected String fpzlDm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double cjhj;
    @XmlElement(required = true, nillable = true)
    protected String mfmc1;
    @XmlElement(required = true, nillable = true)
    protected String esccgluuid;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String mfsfsbh1;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String cglcjfpyjuuid;
    @XmlElement(required = true)
    protected String fpcglcjuuid;
    protected int phcd;
    @XmlElement(required = true)
    protected String cglsjcjlxDm;
    @XmlElement(required = true)
    protected String zfbz1;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fphm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFphm() {
        return fphm;
    }

    /**
     * Sets the value of the fphm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFphm(String value) {
        this.fphm = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the fpkjqkDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpkjqkDm() {
        return fpkjqkDm;
    }

    /**
     * Sets the value of the fpkjqkDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpkjqkDm(String value) {
        this.fpkjqkDm = value;
    }

    /**
     * Gets the value of the mfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfmc() {
        return mfmc;
    }

    /**
     * Sets the value of the mfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfmc(String value) {
        this.mfmc = value;
    }

    /**
     * Gets the value of the mfsfsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfsfsbh() {
        return mfsfsbh;
    }

    /**
     * Sets the value of the mfsfsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfsfsbh(String value) {
        this.mfsfsbh = value;
    }

    /**
     * Gets the value of the kprq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKprq() {
        return kprq;
    }

    /**
     * Sets the value of the kprq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKprq(String value) {
        this.kprq = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the cjhj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCjhj() {
        return cjhj;
    }

    /**
     * Sets the value of the cjhj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCjhj(Double value) {
        this.cjhj = value;
    }

    /**
     * Gets the value of the mfmc1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfmc1() {
        return mfmc1;
    }

    /**
     * Sets the value of the mfmc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfmc1(String value) {
        this.mfmc1 = value;
    }

    /**
     * Gets the value of the esccgluuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsccgluuid() {
        return esccgluuid;
    }

    /**
     * Sets the value of the esccgluuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsccgluuid(String value) {
        this.esccgluuid = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the mfsfsbh1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfsfsbh1() {
        return mfsfsbh1;
    }

    /**
     * Sets the value of the mfsfsbh1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfsfsbh1(String value) {
        this.mfsfsbh1 = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the cglcjfpyjuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCglcjfpyjuuid() {
        return cglcjfpyjuuid;
    }

    /**
     * Sets the value of the cglcjfpyjuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCglcjfpyjuuid(String value) {
        this.cglcjfpyjuuid = value;
    }

    /**
     * Gets the value of the fpcglcjuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpcglcjuuid() {
        return fpcglcjuuid;
    }

    /**
     * Sets the value of the fpcglcjuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpcglcjuuid(String value) {
        this.fpcglcjuuid = value;
    }

    /**
     * Gets the value of the phcd property.
     * 
     */
    public int getPhcd() {
        return phcd;
    }

    /**
     * Sets the value of the phcd property.
     * 
     */
    public void setPhcd(int value) {
        this.phcd = value;
    }

    /**
     * Gets the value of the cglsjcjlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCglsjcjlxDm() {
        return cglsjcjlxDm;
    }

    /**
     * Sets the value of the cglsjcjlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCglsjcjlxDm(String value) {
        this.cglsjcjlxDm = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

}
