//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 建筑业发票存根联采集VO
 * 
 * <p>Java class for FPCglcjJzyfpVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPCglcjJzyfpVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fphm" type="{http://www.chinatax.gov.cn/dataspec/}fphm"/>
 *         &lt;element name="gcxmmc" type="{http://www.chinatax.gov.cn/dataspec/}gcxmmc"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="jzcgluuid" type="{http://www.chinatax.gov.cn/dataspec/}jzcgluuid"/>
 *         &lt;element name="fpkjqkDm" type="{http://www.chinatax.gov.cn/dataspec/}fpkjqkDm"/>
 *         &lt;element name="skfsfsbh" type="{http://www.chinatax.gov.cn/dataspec/}skfsfsbh"/>
 *         &lt;element name="fkfsfsbh" type="{http://www.chinatax.gov.cn/dataspec/}fkfsfsbh"/>
 *         &lt;element name="fkfmc" type="{http://www.chinatax.gov.cn/dataspec/}fkfmc"/>
 *         &lt;element name="kprq" type="{http://www.chinatax.gov.cn/dataspec/}kprq"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="jsxm" type="{http://www.chinatax.gov.cn/dataspec/}jsxm"/>
 *         &lt;element name="je" type="{http://www.chinatax.gov.cn/dataspec/}je"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="cglcjfpyjuuid" type="{http://www.chinatax.gov.cn/dataspec/}cglcjfpyjuuid"/>
 *         &lt;element name="skfmc" type="{http://www.chinatax.gov.cn/dataspec/}skfmc"/>
 *         &lt;element name="wspzhm" type="{http://www.chinatax.gov.cn/dataspec/}wspzhm"/>
 *         &lt;element name="gcxmbh" type="{http://www.chinatax.gov.cn/dataspec/}gcxmbh"/>
 *         &lt;element name="phcd" type="{http://www.chinatax.gov.cn/dataspec/}phcd"/>
 *         &lt;element name="cglsjcjlxDm" type="{http://www.chinatax.gov.cn/dataspec/}cglsjcjlxDm"/>
 *         &lt;element name="fpcglcjuuid" type="{http://www.chinatax.gov.cn/dataspec/}fpcglcjuuid"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPCglcjJzyfpVO", propOrder = {
    "sjgsdq",
    "fphm",
    "gcxmmc",
    "djxh",
    "jzcgluuid",
    "fpkjqkDm",
    "skfsfsbh",
    "fkfsfsbh",
    "fkfmc",
    "kprq",
    "fpDm",
    "fpzlDm",
    "jsxm",
    "je",
    "lrrDm",
    "xgrDm",
    "cglcjfpyjuuid",
    "skfmc",
    "wspzhm",
    "gcxmbh",
    "phcd",
    "cglsjcjlxDm",
    "fpcglcjuuid",
    "zfbz1"
})
public class FPCglcjJzyfpVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fphm;
    @XmlElement(required = true, nillable = true)
    protected String gcxmmc;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String jzcgluuid;
    @XmlElement(required = true, nillable = true)
    protected String fpkjqkDm;
    @XmlElement(required = true, nillable = true)
    protected String skfsfsbh;
    @XmlElement(required = true, nillable = true)
    protected String fkfsfsbh;
    @XmlElement(required = true, nillable = true)
    protected String fkfmc;
    @XmlElement(required = true, nillable = true)
    protected String kprq;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true)
    protected String fpzlDm;
    @XmlElement(required = true, nillable = true)
    protected String jsxm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double je;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String cglcjfpyjuuid;
    @XmlElement(required = true, nillable = true)
    protected String skfmc;
    @XmlElement(required = true, nillable = true)
    protected String wspzhm;
    @XmlElement(required = true, nillable = true)
    protected String gcxmbh;
    protected int phcd;
    @XmlElement(required = true)
    protected String cglsjcjlxDm;
    @XmlElement(required = true)
    protected String fpcglcjuuid;
    @XmlElement(required = true)
    protected String zfbz1;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fphm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFphm() {
        return fphm;
    }

    /**
     * Sets the value of the fphm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFphm(String value) {
        this.fphm = value;
    }

    /**
     * Gets the value of the gcxmmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGcxmmc() {
        return gcxmmc;
    }

    /**
     * Sets the value of the gcxmmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGcxmmc(String value) {
        this.gcxmmc = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the jzcgluuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJzcgluuid() {
        return jzcgluuid;
    }

    /**
     * Sets the value of the jzcgluuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJzcgluuid(String value) {
        this.jzcgluuid = value;
    }

    /**
     * Gets the value of the fpkjqkDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpkjqkDm() {
        return fpkjqkDm;
    }

    /**
     * Sets the value of the fpkjqkDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpkjqkDm(String value) {
        this.fpkjqkDm = value;
    }

    /**
     * Gets the value of the skfsfsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfsfsbh() {
        return skfsfsbh;
    }

    /**
     * Sets the value of the skfsfsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfsfsbh(String value) {
        this.skfsfsbh = value;
    }

    /**
     * Gets the value of the fkfsfsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfsfsbh() {
        return fkfsfsbh;
    }

    /**
     * Sets the value of the fkfsfsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfsfsbh(String value) {
        this.fkfsfsbh = value;
    }

    /**
     * Gets the value of the fkfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfmc() {
        return fkfmc;
    }

    /**
     * Sets the value of the fkfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfmc(String value) {
        this.fkfmc = value;
    }

    /**
     * Gets the value of the kprq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKprq() {
        return kprq;
    }

    /**
     * Sets the value of the kprq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKprq(String value) {
        this.kprq = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the jsxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJsxm() {
        return jsxm;
    }

    /**
     * Sets the value of the jsxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJsxm(String value) {
        this.jsxm = value;
    }

    /**
     * Gets the value of the je property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJe() {
        return je;
    }

    /**
     * Sets the value of the je property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJe(Double value) {
        this.je = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the cglcjfpyjuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCglcjfpyjuuid() {
        return cglcjfpyjuuid;
    }

    /**
     * Sets the value of the cglcjfpyjuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCglcjfpyjuuid(String value) {
        this.cglcjfpyjuuid = value;
    }

    /**
     * Gets the value of the skfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfmc() {
        return skfmc;
    }

    /**
     * Sets the value of the skfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfmc(String value) {
        this.skfmc = value;
    }

    /**
     * Gets the value of the wspzhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWspzhm() {
        return wspzhm;
    }

    /**
     * Sets the value of the wspzhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWspzhm(String value) {
        this.wspzhm = value;
    }

    /**
     * Gets the value of the gcxmbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGcxmbh() {
        return gcxmbh;
    }

    /**
     * Sets the value of the gcxmbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGcxmbh(String value) {
        this.gcxmbh = value;
    }

    /**
     * Gets the value of the phcd property.
     * 
     */
    public int getPhcd() {
        return phcd;
    }

    /**
     * Sets the value of the phcd property.
     * 
     */
    public void setPhcd(int value) {
        this.phcd = value;
    }

    /**
     * Gets the value of the cglsjcjlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCglsjcjlxDm() {
        return cglsjcjlxDm;
    }

    /**
     * Sets the value of the cglsjcjlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCglsjcjlxDm(String value) {
        this.cglsjcjlxDm = value;
    }

    /**
     * Gets the value of the fpcglcjuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpcglcjuuid() {
        return fpcglcjuuid;
    }

    /**
     * Sets the value of the fpcglcjuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpcglcjuuid(String value) {
        this.fpcglcjuuid = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

}
