//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 代开不动产发票VO
 * 
 * <p>Java class for FPDkBdcfpVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPDkBdcfpVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="skfnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}skfnsrsbh"/>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fkfsfzjhm" type="{http://www.chinatax.gov.cn/dataspec/}fkfsfzjhm"/>
 *         &lt;element name="dz" type="{http://www.chinatax.gov.cn/dataspec/}dz"/>
 *         &lt;element name="fkfnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}fkfnsrsbh"/>
 *         &lt;element name="lxdh" type="{http://www.chinatax.gov.cn/dataspec/}lxdh"/>
 *         &lt;element name="lzfpdm" type="{http://www.chinatax.gov.cn/dataspec/}lzfpdm"/>
 *         &lt;element name="fkfmc" type="{http://www.chinatax.gov.cn/dataspec/}fkfmc"/>
 *         &lt;element name="fkfsfzjzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fkfsfzjzlDm"/>
 *         &lt;element name="dksquuid" type="{http://www.chinatax.gov.cn/dataspec/}dksquuid"/>
 *         &lt;element name="lzfphm" type="{http://www.chinatax.gov.cn/dataspec/}lzfphm"/>
 *         &lt;element name="skfsfzjlxDm" type="{http://www.chinatax.gov.cn/dataspec/}skfsfzjlxDm"/>
 *         &lt;element name="gyrmc" type="{http://www.chinatax.gov.cn/dataspec/}gyrmc"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="bdcfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}bdcfpuuid"/>
 *         &lt;element name="sqly" type="{http://www.chinatax.gov.cn/dataspec/}sqly"/>
 *         &lt;element name="fkfdjxh" type="{http://www.chinatax.gov.cn/dataspec/}fkfdjxh"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="skfmc" type="{http://www.chinatax.gov.cn/dataspec/}skfmc"/>
 *         &lt;element name="skfsfzjhm" type="{http://www.chinatax.gov.cn/dataspec/}skfsfzjhm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPDkBdcfpVO", propOrder = {
    "skfnsrsbh",
    "sjgsdq",
    "fkfsfzjhm",
    "dz",
    "fkfnsrsbh",
    "lxdh",
    "lzfpdm",
    "fkfmc",
    "fkfsfzjzlDm",
    "dksquuid",
    "lzfphm",
    "skfsfzjlxDm",
    "gyrmc",
    "lrrDm",
    "bdcfpuuid",
    "sqly",
    "fkfdjxh",
    "xgrDm",
    "skfmc",
    "skfsfzjhm"
})
public class FPDkBdcfpVO {

    @XmlElement(required = true, nillable = true)
    protected String skfnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fkfsfzjhm;
    @XmlElement(required = true, nillable = true)
    protected String dz;
    @XmlElement(required = true, nillable = true)
    protected String fkfnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String lxdh;
    @XmlElement(required = true, nillable = true)
    protected String lzfpdm;
    @XmlElement(required = true, nillable = true)
    protected String fkfmc;
    @XmlElement(required = true, nillable = true)
    protected String fkfsfzjzlDm;
    @XmlElement(required = true, nillable = true)
    protected String dksquuid;
    @XmlElement(required = true, nillable = true)
    protected String lzfphm;
    @XmlElement(required = true, nillable = true)
    protected String skfsfzjlxDm;
    @XmlElement(required = true, nillable = true)
    protected String gyrmc;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String bdcfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String sqly;
    @XmlElement(required = true, nillable = true)
    protected String fkfdjxh;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String skfmc;
    @XmlElement(required = true, nillable = true)
    protected String skfsfzjhm;

    /**
     * Gets the value of the skfnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfnsrsbh() {
        return skfnsrsbh;
    }

    /**
     * Sets the value of the skfnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfnsrsbh(String value) {
        this.skfnsrsbh = value;
    }

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fkfsfzjhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfsfzjhm() {
        return fkfsfzjhm;
    }

    /**
     * Sets the value of the fkfsfzjhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfsfzjhm(String value) {
        this.fkfsfzjhm = value;
    }

    /**
     * Gets the value of the dz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDz() {
        return dz;
    }

    /**
     * Sets the value of the dz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDz(String value) {
        this.dz = value;
    }

    /**
     * Gets the value of the fkfnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfnsrsbh() {
        return fkfnsrsbh;
    }

    /**
     * Sets the value of the fkfnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfnsrsbh(String value) {
        this.fkfnsrsbh = value;
    }

    /**
     * Gets the value of the lxdh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * Sets the value of the lxdh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLxdh(String value) {
        this.lxdh = value;
    }

    /**
     * Gets the value of the lzfpdm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLzfpdm() {
        return lzfpdm;
    }

    /**
     * Sets the value of the lzfpdm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLzfpdm(String value) {
        this.lzfpdm = value;
    }

    /**
     * Gets the value of the fkfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfmc() {
        return fkfmc;
    }

    /**
     * Sets the value of the fkfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfmc(String value) {
        this.fkfmc = value;
    }

    /**
     * Gets the value of the fkfsfzjzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfsfzjzlDm() {
        return fkfsfzjzlDm;
    }

    /**
     * Sets the value of the fkfsfzjzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfsfzjzlDm(String value) {
        this.fkfsfzjzlDm = value;
    }

    /**
     * Gets the value of the dksquuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDksquuid() {
        return dksquuid;
    }

    /**
     * Sets the value of the dksquuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDksquuid(String value) {
        this.dksquuid = value;
    }

    /**
     * Gets the value of the lzfphm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLzfphm() {
        return lzfphm;
    }

    /**
     * Sets the value of the lzfphm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLzfphm(String value) {
        this.lzfphm = value;
    }

    /**
     * Gets the value of the skfsfzjlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfsfzjlxDm() {
        return skfsfzjlxDm;
    }

    /**
     * Sets the value of the skfsfzjlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfsfzjlxDm(String value) {
        this.skfsfzjlxDm = value;
    }

    /**
     * Gets the value of the gyrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGyrmc() {
        return gyrmc;
    }

    /**
     * Sets the value of the gyrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGyrmc(String value) {
        this.gyrmc = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the bdcfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBdcfpuuid() {
        return bdcfpuuid;
    }

    /**
     * Sets the value of the bdcfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBdcfpuuid(String value) {
        this.bdcfpuuid = value;
    }

    /**
     * Gets the value of the sqly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqly() {
        return sqly;
    }

    /**
     * Sets the value of the sqly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqly(String value) {
        this.sqly = value;
    }

    /**
     * Gets the value of the fkfdjxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkfdjxh() {
        return fkfdjxh;
    }

    /**
     * Sets the value of the fkfdjxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkfdjxh(String value) {
        this.fkfdjxh = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the skfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfmc() {
        return skfmc;
    }

    /**
     * Sets the value of the skfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfmc(String value) {
        this.skfmc = value;
    }

    /**
     * Gets the value of the skfsfzjhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkfsfzjhm() {
        return skfsfzjhm;
    }

    /**
     * Sets the value of the skfsfzjhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkfsfzjhm(String value) {
        this.skfsfzjhm = value;
    }

}
