//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 ÏÂÎç CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ·¢Æ±¹ÒÊ§ºËÏúVO
 * 
 * <p>Java class for FPGsshFpzlVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPGsshFpzlVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm" minOccurs="0"/>
 *         &lt;element name="fpzlmc" type="{http://www.chinatax.gov.cn/dataspec/}fpzlmc" minOccurs="0"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm" minOccurs="0"/>
 *         &lt;element name="fpdmmc" type="{http://www.chinatax.gov.cn/dataspec/}fpdmmc" minOccurs="0"/>
 *         &lt;element name="phcd" type="{http://www.chinatax.gov.cn/dataspec/}phcd" minOccurs="0"/>
 *         &lt;element name="jldwDm" type="{http://www.chinatax.gov.cn/dataspec/}jldwDm" minOccurs="0"/>
 *         &lt;element name="fpzg" type="{http://www.chinatax.gov.cn/dataspec/}fpzg" minOccurs="0"/>
 *         &lt;element name="zkdklxDm" type="{http://www.chinatax.gov.cn/dataspec/}zkdklxDm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPGsshFpzlVO", propOrder = {
    "fpzlDm",
    "fpzlmc",
    "fpDm",
    "fpdmmc",
    "phcd",
    "jldwDm",
    "fpzg",
    "zkdklxDm"
})
public class FPGsshFpzlVO {

    protected String fpzlDm;
    protected String fpzlmc;
    protected String fpDm;
    protected String fpdmmc;
    protected Integer phcd;
    protected String jldwDm;
    protected String fpzg;
    protected String zkdklxDm;

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the fpzlmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlmc() {
        return fpzlmc;
    }

    /**
     * Sets the value of the fpzlmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlmc(String value) {
        this.fpzlmc = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the fpdmmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpdmmc() {
        return fpdmmc;
    }

    /**
     * Sets the value of the fpdmmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpdmmc(String value) {
        this.fpdmmc = value;
    }

    /**
     * Gets the value of the phcd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPhcd() {
        return phcd;
    }

    /**
     * Sets the value of the phcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPhcd(Integer value) {
        this.phcd = value;
    }

    /**
     * Gets the value of the jldwDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJldwDm() {
        return jldwDm;
    }

    /**
     * Sets the value of the jldwDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJldwDm(String value) {
        this.jldwDm = value;
    }

    /**
     * Gets the value of the fpzg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzg() {
        return fpzg;
    }

    /**
     * Sets the value of the fpzg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzg(String value) {
        this.fpzg = value;
    }

    /**
     * Gets the value of the zkdklxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZkdklxDm() {
        return zkdklxDm;
    }

    /**
     * Sets the value of the zkdklxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZkdklxDm(String value) {
        this.zkdklxDm = value;
    }

}
