//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 建筑业发票代开申报单
 * 
 * <p>Java class for FPJzyFpdksbdVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPJzyFpdksbdVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}FPFpdksbdVO">
 *       &lt;sequence>
 *         &lt;element name="fpdkJzyfpVO" type="{http://www.chinatax.gov.cn/dataspec/}FPDkJzyfpVO"/>
 *         &lt;element name="fpdkJzyGcxmGrid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="fpdkJzyGcxmGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPDkJzyfpGcxmVO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPJzyFpdksbdVO", propOrder = {
    "fpdkJzyfpVO",
    "fpdkJzyGcxmGrid"
})
public class FPJzyFpdksbdVO
    extends FPFpdksbdVO
{

    @XmlElement(required = true)
    protected FPDkJzyfpVO fpdkJzyfpVO;
    @XmlElement(required = true)
    protected FPJzyFpdksbdVO.FpdkJzyGcxmGrid fpdkJzyGcxmGrid;

    /**
     * Gets the value of the fpdkJzyfpVO property.
     * 
     * @return
     *     possible object is
     *     {@link FPDkJzyfpVO }
     *     
     */
    public FPDkJzyfpVO getFpdkJzyfpVO() {
        return fpdkJzyfpVO;
    }

    /**
     * Sets the value of the fpdkJzyfpVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPDkJzyfpVO }
     *     
     */
    public void setFpdkJzyfpVO(FPDkJzyfpVO value) {
        this.fpdkJzyfpVO = value;
    }

    /**
     * Gets the value of the fpdkJzyGcxmGrid property.
     * 
     * @return
     *     possible object is
     *     {@link FPJzyFpdksbdVO.FpdkJzyGcxmGrid }
     *     
     */
    public FPJzyFpdksbdVO.FpdkJzyGcxmGrid getFpdkJzyGcxmGrid() {
        return fpdkJzyGcxmGrid;
    }

    /**
     * Sets the value of the fpdkJzyGcxmGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPJzyFpdksbdVO.FpdkJzyGcxmGrid }
     *     
     */
    public void setFpdkJzyGcxmGrid(FPJzyFpdksbdVO.FpdkJzyGcxmGrid value) {
        this.fpdkJzyGcxmGrid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="fpdkJzyGcxmGridlb" type="{http://www.chinatax.gov.cn/dataspec/}FPDkJzyfpGcxmVO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fpdkJzyGcxmGridlb"
    })
    public static class FpdkJzyGcxmGrid {

        @XmlElement(required = true)
        protected List<FPDkJzyfpGcxmVO> fpdkJzyGcxmGridlb;

        /**
         * Gets the value of the fpdkJzyGcxmGridlb property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fpdkJzyGcxmGridlb property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFpdkJzyGcxmGridlb().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FPDkJzyfpGcxmVO }
         * 
         * 
         */
        public List<FPDkJzyfpGcxmVO> getFpdkJzyGcxmGridlb() {
            if (fpdkJzyGcxmGridlb == null) {
                fpdkJzyGcxmGridlb = new ArrayList<FPDkJzyfpGcxmVO>();
            }
            return this.fpdkJzyGcxmGridlb;
        }

    }

}
