//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 开具红字运输发票通知单VO
 * 
 * <p>Java class for FPKjhzysfpTzdVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPKjhzysfpTzdVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zgswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}zgswjgDm"/>
 *         &lt;element name="tfrq" type="{http://www.chinatax.gov.cn/dataspec/}tfrq"/>
 *         &lt;element name="dkfpdwnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}dkfpdwnsrsbh"/>
 *         &lt;element name="dkfpdwmc" type="{http://www.chinatax.gov.cn/dataspec/}dkfpdwmc"/>
 *         &lt;element name="yfjehj" type="{http://www.chinatax.gov.cn/dataspec/}yfjehj"/>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="hxbz" type="{http://www.chinatax.gov.cn/dataspec/}hxbz"/>
 *         &lt;element name="sqkjhzhyfply" type="{http://www.chinatax.gov.cn/dataspec/}sqkjhzhyfply"/>
 *         &lt;element name="fhrmc" type="{http://www.chinatax.gov.cn/dataspec/}fhrmc"/>
 *         &lt;element name="shrmc" type="{http://www.chinatax.gov.cn/dataspec/}shrmc"/>
 *         &lt;element name="shrnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}shrnsrsbh"/>
 *         &lt;element name="fphm" type="{http://www.chinatax.gov.cn/dataspec/}fphm"/>
 *         &lt;element name="yfjqtfyjezj" type="{http://www.chinatax.gov.cn/dataspec/}yfjqtfyjezj"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="qtfyxj" type="{http://www.chinatax.gov.cn/dataspec/}qtfyxj"/>
 *         &lt;element name="kjsl" type="{http://www.chinatax.gov.cn/dataspec/}kjsl"/>
 *         &lt;element name="cyfmc" type="{http://www.chinatax.gov.cn/dataspec/}cyfmc"/>
 *         &lt;element name="fhrnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}fhrnsrsbh"/>
 *         &lt;element name="sqdjxh" type="{http://www.chinatax.gov.cn/dataspec/}sqdjxh"/>
 *         &lt;element name="sqrq" type="{http://www.chinatax.gov.cn/dataspec/}sqrq"/>
 *         &lt;element name="cyfzgswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}cyfzgswjgDm"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="swjgjbrDm" type="{http://www.chinatax.gov.cn/dataspec/}swjgjbrDm"/>
 *         &lt;element name="bh" type="{http://www.chinatax.gov.cn/dataspec/}bh"/>
 *         &lt;element name="spfjbr" type="{http://www.chinatax.gov.cn/dataspec/}spfjbr"/>
 *         &lt;element name="spflxDm" type="{http://www.chinatax.gov.cn/dataspec/}spflxDm"/>
 *         &lt;element name="kjse" type="{http://www.chinatax.gov.cn/dataspec/}kjse"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="slswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}slswjgDm"/>
 *         &lt;element name="hzfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}hzfpuuid"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="cyfnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}cyfnsrsbh"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *         &lt;element name="slrq" type="{http://www.chinatax.gov.cn/dataspec/}slrq"/>
 *         &lt;element name="slrDm" type="{http://www.chinatax.gov.cn/dataspec/}slrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPKjhzysfpTzdVO", propOrder = {
    "zgswjgDm",
    "tfrq",
    "dkfpdwnsrsbh",
    "dkfpdwmc",
    "yfjehj",
    "sjgsdq",
    "hxbz",
    "sqkjhzhyfply",
    "fhrmc",
    "shrmc",
    "shrnsrsbh",
    "fphm",
    "yfjqtfyjezj",
    "lcslid",
    "qtfyxj",
    "kjsl",
    "cyfmc",
    "fhrnsrsbh",
    "sqdjxh",
    "sqrq",
    "cyfzgswjgDm",
    "fpDm",
    "swjgjbrDm",
    "bh",
    "spfjbr",
    "spflxDm",
    "kjse",
    "lrrDm",
    "slswjgDm",
    "hzfpuuid",
    "xgrDm",
    "cyfnsrsbh",
    "zfbz1",
    "slrq",
    "slrDm"
})
public class FPKjhzysfpTzdVO {

    @XmlElement(required = true, nillable = true)
    protected String zgswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String tfrq;
    @XmlElement(required = true, nillable = true)
    protected String dkfpdwnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String dkfpdwmc;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double yfjehj;
    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String hxbz;
    @XmlElement(required = true, nillable = true)
    protected String sqkjhzhyfply;
    @XmlElement(required = true, nillable = true)
    protected String fhrmc;
    @XmlElement(required = true, nillable = true)
    protected String shrmc;
    @XmlElement(required = true, nillable = true)
    protected String shrnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String fphm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double yfjqtfyjezj;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double qtfyxj;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double kjsl;
    @XmlElement(required = true, nillable = true)
    protected String cyfmc;
    @XmlElement(required = true, nillable = true)
    protected String fhrnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String sqdjxh;
    @XmlElement(required = true, nillable = true)
    protected String sqrq;
    @XmlElement(required = true, nillable = true)
    protected String cyfzgswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true, nillable = true)
    protected String swjgjbrDm;
    @XmlElement(required = true, nillable = true)
    protected String bh;
    @XmlElement(required = true, nillable = true)
    protected String spfjbr;
    @XmlElement(required = true, nillable = true)
    protected String spflxDm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double kjse;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String slswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String hzfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String cyfnsrsbh;
    @XmlElement(required = true, nillable = true)
    protected String zfbz1;
    @XmlElement(required = true, nillable = true)
    protected String slrq;
    @XmlElement(required = true, nillable = true)
    protected String slrDm;

    /**
     * Gets the value of the zgswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZgswjgDm() {
        return zgswjgDm;
    }

    /**
     * Sets the value of the zgswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZgswjgDm(String value) {
        this.zgswjgDm = value;
    }

    /**
     * Gets the value of the tfrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTfrq() {
        return tfrq;
    }

    /**
     * Sets the value of the tfrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTfrq(String value) {
        this.tfrq = value;
    }

    /**
     * Gets the value of the dkfpdwnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDkfpdwnsrsbh() {
        return dkfpdwnsrsbh;
    }

    /**
     * Sets the value of the dkfpdwnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDkfpdwnsrsbh(String value) {
        this.dkfpdwnsrsbh = value;
    }

    /**
     * Gets the value of the dkfpdwmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDkfpdwmc() {
        return dkfpdwmc;
    }

    /**
     * Sets the value of the dkfpdwmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDkfpdwmc(String value) {
        this.dkfpdwmc = value;
    }

    /**
     * Gets the value of the yfjehj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYfjehj() {
        return yfjehj;
    }

    /**
     * Sets the value of the yfjehj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYfjehj(Double value) {
        this.yfjehj = value;
    }

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the hxbz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHxbz() {
        return hxbz;
    }

    /**
     * Sets the value of the hxbz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHxbz(String value) {
        this.hxbz = value;
    }

    /**
     * Gets the value of the sqkjhzhyfply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqkjhzhyfply() {
        return sqkjhzhyfply;
    }

    /**
     * Sets the value of the sqkjhzhyfply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqkjhzhyfply(String value) {
        this.sqkjhzhyfply = value;
    }

    /**
     * Gets the value of the fhrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFhrmc() {
        return fhrmc;
    }

    /**
     * Sets the value of the fhrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFhrmc(String value) {
        this.fhrmc = value;
    }

    /**
     * Gets the value of the shrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShrmc() {
        return shrmc;
    }

    /**
     * Sets the value of the shrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShrmc(String value) {
        this.shrmc = value;
    }

    /**
     * Gets the value of the shrnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShrnsrsbh() {
        return shrnsrsbh;
    }

    /**
     * Sets the value of the shrnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShrnsrsbh(String value) {
        this.shrnsrsbh = value;
    }

    /**
     * Gets the value of the fphm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFphm() {
        return fphm;
    }

    /**
     * Sets the value of the fphm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFphm(String value) {
        this.fphm = value;
    }

    /**
     * Gets the value of the yfjqtfyjezj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYfjqtfyjezj() {
        return yfjqtfyjezj;
    }

    /**
     * Sets the value of the yfjqtfyjezj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYfjqtfyjezj(Double value) {
        this.yfjqtfyjezj = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the qtfyxj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQtfyxj() {
        return qtfyxj;
    }

    /**
     * Sets the value of the qtfyxj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQtfyxj(Double value) {
        this.qtfyxj = value;
    }

    /**
     * Gets the value of the kjsl property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getKjsl() {
        return kjsl;
    }

    /**
     * Sets the value of the kjsl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKjsl(Double value) {
        this.kjsl = value;
    }

    /**
     * Gets the value of the cyfmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyfmc() {
        return cyfmc;
    }

    /**
     * Sets the value of the cyfmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyfmc(String value) {
        this.cyfmc = value;
    }

    /**
     * Gets the value of the fhrnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFhrnsrsbh() {
        return fhrnsrsbh;
    }

    /**
     * Sets the value of the fhrnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFhrnsrsbh(String value) {
        this.fhrnsrsbh = value;
    }

    /**
     * Gets the value of the sqdjxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdjxh() {
        return sqdjxh;
    }

    /**
     * Sets the value of the sqdjxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdjxh(String value) {
        this.sqdjxh = value;
    }

    /**
     * Gets the value of the sqrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqrq() {
        return sqrq;
    }

    /**
     * Sets the value of the sqrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqrq(String value) {
        this.sqrq = value;
    }

    /**
     * Gets the value of the cyfzgswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyfzgswjgDm() {
        return cyfzgswjgDm;
    }

    /**
     * Sets the value of the cyfzgswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyfzgswjgDm(String value) {
        this.cyfzgswjgDm = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the swjgjbrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwjgjbrDm() {
        return swjgjbrDm;
    }

    /**
     * Sets the value of the swjgjbrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwjgjbrDm(String value) {
        this.swjgjbrDm = value;
    }

    /**
     * Gets the value of the bh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBh() {
        return bh;
    }

    /**
     * Sets the value of the bh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBh(String value) {
        this.bh = value;
    }

    /**
     * Gets the value of the spfjbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpfjbr() {
        return spfjbr;
    }

    /**
     * Sets the value of the spfjbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpfjbr(String value) {
        this.spfjbr = value;
    }

    /**
     * Gets the value of the spflxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpflxDm() {
        return spflxDm;
    }

    /**
     * Sets the value of the spflxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpflxDm(String value) {
        this.spflxDm = value;
    }

    /**
     * Gets the value of the kjse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getKjse() {
        return kjse;
    }

    /**
     * Sets the value of the kjse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKjse(Double value) {
        this.kjse = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the slswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlswjgDm() {
        return slswjgDm;
    }

    /**
     * Sets the value of the slswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlswjgDm(String value) {
        this.slswjgDm = value;
    }

    /**
     * Gets the value of the hzfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHzfpuuid() {
        return hzfpuuid;
    }

    /**
     * Sets the value of the hzfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHzfpuuid(String value) {
        this.hzfpuuid = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the cyfnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyfnsrsbh() {
        return cyfnsrsbh;
    }

    /**
     * Sets the value of the cyfnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyfnsrsbh(String value) {
        this.cyfnsrsbh = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

    /**
     * Gets the value of the slrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrq() {
        return slrq;
    }

    /**
     * Sets the value of the slrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrq(String value) {
        this.slrq = value;
    }

    /**
     * Gets the value of the slrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlrDm() {
        return slrDm;
    }

    /**
     * Sets the value of the slrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlrDm(String value) {
        this.slrDm = value;
    }

}
