//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 ÏÂÎç CST 
//


package cn.gov.chinatax.hxzg.fp;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * VO
 * 
 * <p>Java class for FPPzhdxxLjgpjeVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPPzhdxxLjgpjeVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="yxqq" type="{http://www.chinatax.gov.cn/dataspec/}yxqq"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="ljgpje" type="{http://www.chinatax.gov.cn/dataspec/}ljgpje"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="ljgpje" type="{http://www.chinatax.gov.cn/dataspec/}ljgpje"/>
 *         &lt;element name="pzhdxxuuid" type="{http://www.chinatax.gov.cn/dataspec/}pzhdxxuuid"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="yxbz" type="{http://www.chinatax.gov.cn/dataspec/}yxbz"/>
 *         &lt;element name="yxqz" type="{http://www.chinatax.gov.cn/dataspec/}yxqz"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPPzhdxxLjgpjeVO", propOrder = {
    "content"
})
public class FPPzhdxxLjgpjeVO {

    @XmlElementRefs({
        @XmlElementRef(name = "ljgpje", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "pzhdxxuuid", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "sjgsdq", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "yxbz", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "yxqq", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "yxqz", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "xgrDm", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "lrrDm", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class),
        @XmlElementRef(name = "djxh", namespace = "http://www.chinatax.gov.cn/dataspec/", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends Serializable>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Sjgsdq" is used by two different parts of a schema. See: 
     * line 10854 of file:/D:/jxdb/TaxMLPublicFPType.xsd
     * line 10844 of file:/D:/jxdb/TaxMLPublicFPType.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.content;
    }

}
