//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票实物盘存VO
 * 
 * <p>Java class for FPSwpcVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwpcVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="fpkfgtDm" type="{http://www.chinatax.gov.cn/dataspec/}fpkfgtDm"/>
 *         &lt;element name="fpzzhm" type="{http://www.chinatax.gov.cn/dataspec/}fpzzhm"/>
 *         &lt;element name="zfrq1" type="{http://www.chinatax.gov.cn/dataspec/}zfrq1"/>
 *         &lt;element name="bfs" type="{http://www.chinatax.gov.cn/dataspec/}bfs"/>
 *         &lt;element name="dwslDm" type="{http://www.chinatax.gov.cn/dataspec/}dwslDm"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="bz" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *         &lt;element name="fpqshm" type="{http://www.chinatax.gov.cn/dataspec/}fpqshm"/>
 *         &lt;element name="fs" type="{http://www.chinatax.gov.cn/dataspec/}fs"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="pcjcrmc" type="{http://www.chinatax.gov.cn/dataspec/}pcjcrmc"/>
 *         &lt;element name="pcrq" type="{http://www.chinatax.gov.cn/dataspec/}pcrq"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="swpcuuid" type="{http://www.chinatax.gov.cn/dataspec/}swpcuuid"/>
 *         &lt;element name="pcjcrDm" type="{http://www.chinatax.gov.cn/dataspec/}pcjcrDm"/>
 *         &lt;element name="zfrDm" type="{http://www.chinatax.gov.cn/dataspec/}zfrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="swjgDm" type="{http://www.chinatax.gov.cn/dataspec/}swjgDm"/>
 *         &lt;element name="pcrDm" type="{http://www.chinatax.gov.cn/dataspec/}pcrDm"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *         &lt;element name="pcjcrq" type="{http://www.chinatax.gov.cn/dataspec/}pcjcrq"/>
 *         &lt;element name="fpztDm" type="{http://www.chinatax.gov.cn/dataspec/}fpztDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwpcVO", propOrder = {
    "sjgsdq",
    "fpzlDm",
    "fpkfgtDm",
    "fpzzhm",
    "zfrq1",
    "bfs",
    "dwslDm",
    "lcslid",
    "bz",
    "fpqshm",
    "fs",
    "fpDm",
    "pcjcrmc",
    "pcrq",
    "lrrDm",
    "swpcuuid",
    "pcjcrDm",
    "zfrDm",
    "xgrDm",
    "swjgDm",
    "pcrDm",
    "zfbz1",
    "pcjcrq",
    "fpztDm"
})
@XmlSeeAlso({
    FPSwpcVOEx.class
})
public class FPSwpcVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fpzlDm;
    @XmlElement(required = true, nillable = true)
    protected String fpkfgtDm;
    @XmlElement(required = true, nillable = true)
    protected String fpzzhm;
    @XmlElement(required = true, nillable = true)
    protected String zfrq1;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long bfs;
    @XmlElement(required = true, nillable = true)
    protected String dwslDm;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String bz;
    @XmlElement(required = true, nillable = true)
    protected String fpqshm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double fs;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true, nillable = true)
    protected String pcjcrmc;
    @XmlElement(required = true, nillable = true)
    protected String pcrq;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String swpcuuid;
    @XmlElement(required = true, nillable = true)
    protected String pcjcrDm;
    @XmlElement(required = true, nillable = true)
    protected String zfrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String swjgDm;
    @XmlElement(required = true, nillable = true)
    protected String pcrDm;
    @XmlElement(required = true, nillable = true)
    protected String zfbz1;
    @XmlElement(required = true, nillable = true)
    protected String pcjcrq;
    @XmlElement(required = true, nillable = true)
    protected String fpztDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the fpkfgtDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpkfgtDm() {
        return fpkfgtDm;
    }

    /**
     * Sets the value of the fpkfgtDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpkfgtDm(String value) {
        this.fpkfgtDm = value;
    }

    /**
     * Gets the value of the fpzzhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzzhm() {
        return fpzzhm;
    }

    /**
     * Sets the value of the fpzzhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzzhm(String value) {
        this.fpzzhm = value;
    }

    /**
     * Gets the value of the zfrq1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrq1() {
        return zfrq1;
    }

    /**
     * Sets the value of the zfrq1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrq1(String value) {
        this.zfrq1 = value;
    }

    /**
     * Gets the value of the bfs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBfs() {
        return bfs;
    }

    /**
     * Sets the value of the bfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBfs(Long value) {
        this.bfs = value;
    }

    /**
     * Gets the value of the dwslDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDwslDm() {
        return dwslDm;
    }

    /**
     * Sets the value of the dwslDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDwslDm(String value) {
        this.dwslDm = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the bz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBz() {
        return bz;
    }

    /**
     * Sets the value of the bz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBz(String value) {
        this.bz = value;
    }

    /**
     * Gets the value of the fpqshm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpqshm() {
        return fpqshm;
    }

    /**
     * Sets the value of the fpqshm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpqshm(String value) {
        this.fpqshm = value;
    }

    /**
     * Gets the value of the fs property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFs() {
        return fs;
    }

    /**
     * Sets the value of the fs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFs(Double value) {
        this.fs = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the pcjcrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcjcrmc() {
        return pcjcrmc;
    }

    /**
     * Sets the value of the pcjcrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcjcrmc(String value) {
        this.pcjcrmc = value;
    }

    /**
     * Gets the value of the pcrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcrq() {
        return pcrq;
    }

    /**
     * Sets the value of the pcrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcrq(String value) {
        this.pcrq = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the swpcuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwpcuuid() {
        return swpcuuid;
    }

    /**
     * Sets the value of the swpcuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwpcuuid(String value) {
        this.swpcuuid = value;
    }

    /**
     * Gets the value of the pcjcrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcjcrDm() {
        return pcjcrDm;
    }

    /**
     * Sets the value of the pcjcrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcjcrDm(String value) {
        this.pcjcrDm = value;
    }

    /**
     * Gets the value of the zfrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrDm() {
        return zfrDm;
    }

    /**
     * Sets the value of the zfrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrDm(String value) {
        this.zfrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the swjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwjgDm() {
        return swjgDm;
    }

    /**
     * Sets the value of the swjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwjgDm(String value) {
        this.swjgDm = value;
    }

    /**
     * Gets the value of the pcrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcrDm() {
        return pcrDm;
    }

    /**
     * Sets the value of the pcrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcrDm(String value) {
        this.pcrDm = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

    /**
     * Gets the value of the pcjcrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcjcrq() {
        return pcjcrq;
    }

    /**
     * Sets the value of the pcjcrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcjcrq(String value) {
        this.pcjcrq = value;
    }

    /**
     * Gets the value of the fpztDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpztDm() {
        return fpztDm;
    }

    /**
     * Sets the value of the fpztDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpztDm(String value) {
        this.fpztDm = value;
    }

}
