//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务行政许可增值税专用发票最高限额VO
 * 
 * <p>Java class for FPSwxzxkZgxeVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwxzxkZgxeVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="swxzxkuuid" type="{http://www.chinatax.gov.cn/dataspec/}swxzxkuuid"/>
 *         &lt;element name="kpxeuuid" type="{http://www.chinatax.gov.cn/dataspec/}kpxeuuid"/>
 *         &lt;element name="fpzgkpxeDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzgkpxeDm"/>
 *         &lt;element name="swxzxkxmDm" type="{http://www.chinatax.gov.cn/dataspec/}swxzxkxmDm"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwxzxkZgxeVO", propOrder = {
    "sjgsdq",
    "fpzlDm",
    "swxzxkuuid",
    "kpxeuuid",
    "fpzgkpxeDm",
    "swxzxkxmDm",
    "lrrDm",
    "xgrDm"
})
public class FPSwxzxkZgxeVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fpzlDm;
    @XmlElement(required = true, nillable = true)
    protected String swxzxkuuid;
    @XmlElement(required = true, nillable = true)
    protected String kpxeuuid;
    @XmlElement(required = true, nillable = true)
    protected String fpzgkpxeDm;
    @XmlElement(required = true, nillable = true)
    protected String swxzxkxmDm;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the swxzxkuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwxzxkuuid() {
        return swxzxkuuid;
    }

    /**
     * Sets the value of the swxzxkuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwxzxkuuid(String value) {
        this.swxzxkuuid = value;
    }

    /**
     * Gets the value of the kpxeuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpxeuuid() {
        return kpxeuuid;
    }

    /**
     * Sets the value of the kpxeuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpxeuuid(String value) {
        this.kpxeuuid = value;
    }

    /**
     * Gets the value of the fpzgkpxeDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzgkpxeDm() {
        return fpzgkpxeDm;
    }

    /**
     * Sets the value of the fpzgkpxeDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzgkpxeDm(String value) {
        this.fpzgkpxeDm = value;
    }

    /**
     * Gets the value of the swxzxkxmDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwxzxkxmDm() {
        return swxzxkxmDm;
    }

    /**
     * Sets the value of the swxzxkxmDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwxzxkxmDm(String value) {
        this.swxzxkxmDm = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

}
