//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务行政许可变动情况证件明细VO
 * 
 * <p>Java class for FPSwxzxkBdqkZjmxVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwxzxkBdqkZjmxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="sl" type="{http://www.chinatax.gov.cn/dataspec/}sl"/>
 *         &lt;element name="bdswxzxkuuid" type="{http://www.chinatax.gov.cn/dataspec/}bdswxzxkuuid"/>
 *         &lt;element name="swxzxkzjmc" type="{http://www.chinatax.gov.cn/dataspec/}swxzxkzjmc"/>
 *         &lt;element name="bdswxzxkzjmxuuid" type="{http://www.chinatax.gov.cn/dataspec/}bdswxzxkzjmxuuid"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwxzxkBdqkZjmxVO", propOrder = {
    "sjgsdq",
    "sl",
    "bdswxzxkuuid",
    "swxzxkzjmc",
    "bdswxzxkzjmxuuid",
    "lrrDm",
    "xgrDm"
})
public class FPSwxzxkBdqkZjmxVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sl;
    @XmlElement(required = true, nillable = true)
    protected String bdswxzxkuuid;
    @XmlElement(required = true, nillable = true)
    protected String swxzxkzjmc;
    @XmlElement(required = true, nillable = true)
    protected String bdswxzxkzjmxuuid;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the sl property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSl() {
        return sl;
    }

    /**
     * Sets the value of the sl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSl(Double value) {
        this.sl = value;
    }

    /**
     * Gets the value of the bdswxzxkuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBdswxzxkuuid() {
        return bdswxzxkuuid;
    }

    /**
     * Sets the value of the bdswxzxkuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBdswxzxkuuid(String value) {
        this.bdswxzxkuuid = value;
    }

    /**
     * Gets the value of the swxzxkzjmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwxzxkzjmc() {
        return swxzxkzjmc;
    }

    /**
     * Sets the value of the swxzxkzjmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwxzxkzjmc(String value) {
        this.swxzxkzjmc = value;
    }

    /**
     * Gets the value of the bdswxzxkzjmxuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBdswxzxkzjmxuuid() {
        return bdswxzxkzjmxuuid;
    }

    /**
     * Sets the value of the bdswxzxkzjmxuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBdswxzxkzjmxuuid(String value) {
        this.bdswxzxkzjmxuuid = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

}
