//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务行政许可承印发票信息申请审批VO
 * 
 * <p>Java class for FPSwxzxkCyfpxxSqspVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwxzxkCyfpxxSqspVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="scrDm" type="{http://www.chinatax.gov.cn/dataspec/}scrDm"/>
 *         &lt;element name="hdslid" type="{http://www.chinatax.gov.cn/dataspec/}hdslid"/>
 *         &lt;element name="scrq" type="{http://www.chinatax.gov.cn/dataspec/}scrq"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="cyfpsqspuuid" type="{http://www.chinatax.gov.cn/dataspec/}cyfpsqspuuid"/>
 *         &lt;element name="xkyxqz" type="{http://www.chinatax.gov.cn/dataspec/}xkyxqz"/>
 *         &lt;element name="scjgscyjDm" type="{http://www.chinatax.gov.cn/dataspec/}scjgscyjDm"/>
 *         &lt;element name="fpbmyxm" type="{http://www.chinatax.gov.cn/dataspec/}fpbmyxm"/>
 *         &lt;element name="xkyxqq" type="{http://www.chinatax.gov.cn/dataspec/}xkyxqq"/>
 *         &lt;element name="scswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}scswjgDm"/>
 *         &lt;element name="fpbgyxm" type="{http://www.chinatax.gov.cn/dataspec/}fpbgyxm"/>
 *         &lt;element name="fpjyyxm" type="{http://www.chinatax.gov.cn/dataspec/}fpjyyxm"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="scjgscyjsm" type="{http://www.chinatax.gov.cn/dataspec/}scjgscyjsm"/>
 *         &lt;element name="nsrmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="cysctj" type="{http://www.chinatax.gov.cn/dataspec/}cysctj"/>
 *         &lt;element name="fpywyxm" type="{http://www.chinatax.gov.cn/dataspec/}fpywyxm"/>
 *         &lt;element name="cybzmc" type="{http://www.chinatax.gov.cn/dataspec/}cybzmc"/>
 *         &lt;element name="cyycmc" type="{http://www.chinatax.gov.cn/dataspec/}cyycmc"/>
 *         &lt;element name="fppbyxm" type="{http://www.chinatax.gov.cn/dataspec/}fppbyxm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwxzxkCyfpxxSqspVO", propOrder = {
    "sjgsdq",
    "djxh",
    "scrDm",
    "hdslid",
    "scrq",
    "lcslid",
    "cyfpsqspuuid",
    "xkyxqz",
    "scjgscyjDm",
    "fpbmyxm",
    "xkyxqq",
    "scswjgDm",
    "fpbgyxm",
    "fpjyyxm",
    "lrrDm",
    "scjgscyjsm",
    "nsrmc",
    "xgrDm",
    "cysctj",
    "fpywyxm",
    "cybzmc",
    "cyycmc",
    "fppbyxm"
})
public class FPSwxzxkCyfpxxSqspVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String scrDm;
    @XmlElement(required = true, nillable = true)
    protected String hdslid;
    @XmlElement(required = true, nillable = true)
    protected String scrq;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String cyfpsqspuuid;
    @XmlElement(required = true, nillable = true)
    protected String xkyxqz;
    @XmlElement(required = true, nillable = true)
    protected String scjgscyjDm;
    @XmlElement(required = true, nillable = true)
    protected String fpbmyxm;
    @XmlElement(required = true, nillable = true)
    protected String xkyxqq;
    @XmlElement(required = true, nillable = true)
    protected String scswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String fpbgyxm;
    @XmlElement(required = true, nillable = true)
    protected String fpjyyxm;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String scjgscyjsm;
    @XmlElement(required = true, nillable = true)
    protected String nsrmc;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String cysctj;
    @XmlElement(required = true, nillable = true)
    protected String fpywyxm;
    @XmlElement(required = true, nillable = true)
    protected String cybzmc;
    @XmlElement(required = true, nillable = true)
    protected String cyycmc;
    @XmlElement(required = true, nillable = true)
    protected String fppbyxm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the scrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrDm() {
        return scrDm;
    }

    /**
     * Sets the value of the scrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrDm(String value) {
        this.scrDm = value;
    }

    /**
     * Gets the value of the hdslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdslid() {
        return hdslid;
    }

    /**
     * Sets the value of the hdslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdslid(String value) {
        this.hdslid = value;
    }

    /**
     * Gets the value of the scrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrq() {
        return scrq;
    }

    /**
     * Sets the value of the scrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrq(String value) {
        this.scrq = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the cyfpsqspuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyfpsqspuuid() {
        return cyfpsqspuuid;
    }

    /**
     * Sets the value of the cyfpsqspuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyfpsqspuuid(String value) {
        this.cyfpsqspuuid = value;
    }

    /**
     * Gets the value of the xkyxqz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXkyxqz() {
        return xkyxqz;
    }

    /**
     * Sets the value of the xkyxqz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXkyxqz(String value) {
        this.xkyxqz = value;
    }

    /**
     * Gets the value of the scjgscyjDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScjgscyjDm() {
        return scjgscyjDm;
    }

    /**
     * Sets the value of the scjgscyjDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScjgscyjDm(String value) {
        this.scjgscyjDm = value;
    }

    /**
     * Gets the value of the fpbmyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpbmyxm() {
        return fpbmyxm;
    }

    /**
     * Sets the value of the fpbmyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpbmyxm(String value) {
        this.fpbmyxm = value;
    }

    /**
     * Gets the value of the xkyxqq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXkyxqq() {
        return xkyxqq;
    }

    /**
     * Sets the value of the xkyxqq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXkyxqq(String value) {
        this.xkyxqq = value;
    }

    /**
     * Gets the value of the scswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScswjgDm() {
        return scswjgDm;
    }

    /**
     * Sets the value of the scswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScswjgDm(String value) {
        this.scswjgDm = value;
    }

    /**
     * Gets the value of the fpbgyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpbgyxm() {
        return fpbgyxm;
    }

    /**
     * Sets the value of the fpbgyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpbgyxm(String value) {
        this.fpbgyxm = value;
    }

    /**
     * Gets the value of the fpjyyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpjyyxm() {
        return fpjyyxm;
    }

    /**
     * Sets the value of the fpjyyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpjyyxm(String value) {
        this.fpjyyxm = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the scjgscyjsm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScjgscyjsm() {
        return scjgscyjsm;
    }

    /**
     * Sets the value of the scjgscyjsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScjgscyjsm(String value) {
        this.scjgscyjsm = value;
    }

    /**
     * Gets the value of the nsrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsrmc() {
        return nsrmc;
    }

    /**
     * Sets the value of the nsrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsrmc(String value) {
        this.nsrmc = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the cysctj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCysctj() {
        return cysctj;
    }

    /**
     * Sets the value of the cysctj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCysctj(String value) {
        this.cysctj = value;
    }

    /**
     * Gets the value of the fpywyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpywyxm() {
        return fpywyxm;
    }

    /**
     * Sets the value of the fpywyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpywyxm(String value) {
        this.fpywyxm = value;
    }

    /**
     * Gets the value of the cybzmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCybzmc() {
        return cybzmc;
    }

    /**
     * Sets the value of the cybzmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCybzmc(String value) {
        this.cybzmc = value;
    }

    /**
     * Gets the value of the cyycmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyycmc() {
        return cyycmc;
    }

    /**
     * Sets the value of the cyycmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyycmc(String value) {
        this.cyycmc = value;
    }

    /**
     * Gets the value of the fppbyxm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFppbyxm() {
        return fppbyxm;
    }

    /**
     * Sets the value of the fppbyxm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFppbyxm(String value) {
        this.fppbyxm = value;
    }

}
