//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 特别纳税监控管理考核统计表VO
 * 
 * <p>Java class for FPTssjcjTbnsjkglkhtjbVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPTssjcjTbnsjkglkhtjbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ybzzse" type="{http://www.chinatax.gov.cn/dataspec/}ybzzse"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="uuid" type="{http://www.chinatax.gov.cn/dataspec/}uuid"/>
 *         &lt;element name="yydjapajbh" type="{http://www.chinatax.gov.cn/dataspec/}yydjapajbh"/>
 *         &lt;element name="tbnstzdclxDm" type="{http://www.chinatax.gov.cn/dataspec/}tbnstzdclxDm"/>
 *         &lt;element name="jkqqk" type="{http://www.chinatax.gov.cn/dataspec/}jkqqk"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="qysdstzqktzynsdse" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="jkhqk" type="{http://www.chinatax.gov.cn/dataspec/}jkhqk"/>
 *         &lt;element name="ybyyse" type="{http://www.chinatax.gov.cn/dataspec/}ybyyse"/>
 *         &lt;element name="ybsdse" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="tzzzsyssre" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="ybqtse" type="{http://www.chinatax.gov.cn/dataspec/}ybqtse"/>
 *         &lt;element name="nsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}nsrsbh"/>
 *         &lt;element name="tbnsdcajbh" type="{http://www.chinatax.gov.cn/dataspec/}tbnsdcajbh"/>
 *         &lt;element name="tzxfsyssre" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="qtsyssre" type="{http://www.chinatax.gov.cn/dataspec/}qtsyssre"/>
 *         &lt;element name="mxuuid" type="{http://www.chinatax.gov.cn/dataspec/}mxuuid"/>
 *         &lt;element name="ybxfse" type="{http://www.chinatax.gov.cn/dataspec/}ybxfse"/>
 *         &lt;element name="tzyysyssre" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="tbnsjkglhjDm" type="{http://www.chinatax.gov.cn/dataspec/}tbnsjkglhjDm"/>
 *         &lt;element name="ajmc" type="{http://www.chinatax.gov.cn/dataspec/}ajmc"/>
 *         &lt;element name="yydjapajmc" type="{http://www.chinatax.gov.cn/dataspec/}yydjapajmc"/>
 *         &lt;element name="nsrmc" type="{http://www.chinatax.gov.cn/dataspec/}nsrmc"/>
 *         &lt;element name="jknd" type="{http://www.chinatax.gov.cn/dataspec/}jknd"/>
 *         &lt;element name="gtzrmbje" type="{http://www.chinatax.gov.cn/dataspec/}gtzrmbje"/>
 *         &lt;element name="qysdstzqkmbkse" type="{http://www.chinatax.gov.cn/dataspec/}se"/>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPTssjcjTbnsjkglkhtjbVO", propOrder = {
    "ybzzse",
    "lrrDm",
    "uuid",
    "yydjapajbh",
    "tbnstzdclxDm",
    "jkqqk",
    "xgrDm",
    "djxh",
    "qysdstzqktzynsdse",
    "jkhqk",
    "ybyyse",
    "ybsdse",
    "tzzzsyssre",
    "ybqtse",
    "nsrsbh",
    "tbnsdcajbh",
    "tzxfsyssre",
    "qtsyssre",
    "mxuuid",
    "ybxfse",
    "tzyysyssre",
    "tbnsjkglhjDm",
    "ajmc",
    "yydjapajmc",
    "nsrmc",
    "jknd",
    "gtzrmbje",
    "qysdstzqkmbkse",
    "sjgsdq"
})
public class FPTssjcjTbnsjkglkhtjbVO {

    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybzzse;
    @XmlElement(required = true)
    protected String lrrDm;
    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true, nillable = true)
    protected String yydjapajbh;
    @XmlElement(required = true)
    protected String tbnstzdclxDm;
    @XmlElement(required = true)
    protected String jkqqk;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true)
    protected String djxh;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double qysdstzqktzynsdse;
    @XmlElement(required = true)
    protected String jkhqk;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybyyse;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybsdse;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double tzzzsyssre;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybqtse;
    @XmlElement(required = true)
    protected String nsrsbh;
    @XmlElement(required = true)
    protected String tbnsdcajbh;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double tzxfsyssre;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double qtsyssre;
    @XmlElement(required = true)
    protected String mxuuid;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ybxfse;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double tzyysyssre;
    @XmlElement(required = true)
    protected String tbnsjkglhjDm;
    @XmlElement(required = true)
    protected String ajmc;
    @XmlElement(required = true, nillable = true)
    protected String yydjapajmc;
    @XmlElement(required = true)
    protected String nsrmc;
    @XmlElement(required = true)
    protected String jknd;
    protected double gtzrmbje;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double qysdstzqkmbkse;
    @XmlElement(required = true)
    protected String sjgsdq;

    /**
     * Gets the value of the ybzzse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYbzzse() {
        return ybzzse;
    }

    /**
     * Sets the value of the ybzzse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYbzzse(Double value) {
        this.ybzzse = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the yydjapajbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYydjapajbh() {
        return yydjapajbh;
    }

    /**
     * Sets the value of the yydjapajbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYydjapajbh(String value) {
        this.yydjapajbh = value;
    }

    /**
     * Gets the value of the tbnstzdclxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbnstzdclxDm() {
        return tbnstzdclxDm;
    }

    /**
     * Sets the value of the tbnstzdclxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbnstzdclxDm(String value) {
        this.tbnstzdclxDm = value;
    }

    /**
     * Gets the value of the jkqqk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJkqqk() {
        return jkqqk;
    }

    /**
     * Sets the value of the jkqqk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJkqqk(String value) {
        this.jkqqk = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the qysdstzqktzynsdse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQysdstzqktzynsdse() {
        return qysdstzqktzynsdse;
    }

    /**
     * Sets the value of the qysdstzqktzynsdse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQysdstzqktzynsdse(Double value) {
        this.qysdstzqktzynsdse = value;
    }

    /**
     * Gets the value of the jkhqk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJkhqk() {
        return jkhqk;
    }

    /**
     * Sets the value of the jkhqk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJkhqk(String value) {
        this.jkhqk = value;
    }

    /**
     * Gets the value of the ybyyse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYbyyse() {
        return ybyyse;
    }

    /**
     * Sets the value of the ybyyse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYbyyse(Double value) {
        this.ybyyse = value;
    }

    /**
     * Gets the value of the ybsdse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYbsdse() {
        return ybsdse;
    }

    /**
     * Sets the value of the ybsdse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYbsdse(Double value) {
        this.ybsdse = value;
    }

    /**
     * Gets the value of the tzzzsyssre property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTzzzsyssre() {
        return tzzzsyssre;
    }

    /**
     * Sets the value of the tzzzsyssre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTzzzsyssre(Double value) {
        this.tzzzsyssre = value;
    }

    /**
     * Gets the value of the ybqtse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYbqtse() {
        return ybqtse;
    }

    /**
     * Sets the value of the ybqtse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYbqtse(Double value) {
        this.ybqtse = value;
    }

    /**
     * Gets the value of the nsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsrsbh() {
        return nsrsbh;
    }

    /**
     * Sets the value of the nsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsrsbh(String value) {
        this.nsrsbh = value;
    }

    /**
     * Gets the value of the tbnsdcajbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbnsdcajbh() {
        return tbnsdcajbh;
    }

    /**
     * Sets the value of the tbnsdcajbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbnsdcajbh(String value) {
        this.tbnsdcajbh = value;
    }

    /**
     * Gets the value of the tzxfsyssre property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTzxfsyssre() {
        return tzxfsyssre;
    }

    /**
     * Sets the value of the tzxfsyssre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTzxfsyssre(Double value) {
        this.tzxfsyssre = value;
    }

    /**
     * Gets the value of the qtsyssre property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQtsyssre() {
        return qtsyssre;
    }

    /**
     * Sets the value of the qtsyssre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQtsyssre(Double value) {
        this.qtsyssre = value;
    }

    /**
     * Gets the value of the mxuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMxuuid() {
        return mxuuid;
    }

    /**
     * Sets the value of the mxuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMxuuid(String value) {
        this.mxuuid = value;
    }

    /**
     * Gets the value of the ybxfse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYbxfse() {
        return ybxfse;
    }

    /**
     * Sets the value of the ybxfse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYbxfse(Double value) {
        this.ybxfse = value;
    }

    /**
     * Gets the value of the tzyysyssre property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTzyysyssre() {
        return tzyysyssre;
    }

    /**
     * Sets the value of the tzyysyssre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTzyysyssre(Double value) {
        this.tzyysyssre = value;
    }

    /**
     * Gets the value of the tbnsjkglhjDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbnsjkglhjDm() {
        return tbnsjkglhjDm;
    }

    /**
     * Sets the value of the tbnsjkglhjDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbnsjkglhjDm(String value) {
        this.tbnsjkglhjDm = value;
    }

    /**
     * Gets the value of the ajmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAjmc() {
        return ajmc;
    }

    /**
     * Sets the value of the ajmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAjmc(String value) {
        this.ajmc = value;
    }

    /**
     * Gets the value of the yydjapajmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYydjapajmc() {
        return yydjapajmc;
    }

    /**
     * Sets the value of the yydjapajmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYydjapajmc(String value) {
        this.yydjapajmc = value;
    }

    /**
     * Gets the value of the nsrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsrmc() {
        return nsrmc;
    }

    /**
     * Sets the value of the nsrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsrmc(String value) {
        this.nsrmc = value;
    }

    /**
     * Gets the value of the jknd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJknd() {
        return jknd;
    }

    /**
     * Sets the value of the jknd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJknd(String value) {
        this.jknd = value;
    }

    /**
     * Gets the value of the gtzrmbje property.
     * 
     */
    public double getGtzrmbje() {
        return gtzrmbje;
    }

    /**
     * Sets the value of the gtzrmbje property.
     * 
     */
    public void setGtzrmbje(double value) {
        this.gtzrmbje = value;
    }

    /**
     * Gets the value of the qysdstzqkmbkse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQysdstzqkmbkse() {
        return qysdstzqkmbkse;
    }

    /**
     * Sets the value of the qysdstzqkmbkse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQysdstzqkmbkse(Double value) {
        this.qysdstzqkmbkse = value;
    }

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

}
