//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 已认证增值税扣税凭证清单申请抵扣货运发票VO
 * 
 * <p>Java class for FPYrzzzskspzqdSqdkhyfpVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPYrzzzskspzqdSqdkhyfpVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="sqdkglnhhwysytyfpjsdkdkse" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfpjsdkdkse"/>
 *         &lt;element name="sqdkglnhhwysytyfphm" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfphm"/>
 *         &lt;element name="hyfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}hyfpuuid"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="sqdkhyfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}sqdkhyfpuuid"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="sqdkglnhhwysytyfpkpdwnsrmc" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfpkpdwnsrmc"/>
 *         &lt;element name="sqdkglnhhwysytyfpyfje" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfpyfje"/>
 *         &lt;element name="sqdkglnhhwysytyfpDm" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfpDm"/>
 *         &lt;element name="sqdkglnhhwysytyfpkpdwnsrsbh" type="{http://www.chinatax.gov.cn/dataspec/}sqdkglnhhwysytyfpkpdwnsrsbh"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPYrzzzskspzqdSqdkhyfpVO", propOrder = {
    "sjgsdq",
    "sqdkglnhhwysytyfpjsdkdkse",
    "sqdkglnhhwysytyfphm",
    "hyfpuuid",
    "lrrDm",
    "sqdkhyfpuuid",
    "xgrDm",
    "sqdkglnhhwysytyfpkpdwnsrmc",
    "sqdkglnhhwysytyfpyfje",
    "sqdkglnhhwysytyfpDm",
    "sqdkglnhhwysytyfpkpdwnsrsbh"
})
public class FPYrzzzskspzqdSqdkhyfpVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sqdkglnhhwysytyfpjsdkdkse;
    @XmlElement(required = true, nillable = true)
    protected String sqdkglnhhwysytyfphm;
    @XmlElement(required = true, nillable = true)
    protected String hyfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String sqdkhyfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String sqdkglnhhwysytyfpkpdwnsrmc;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sqdkglnhhwysytyfpyfje;
    @XmlElement(required = true, nillable = true)
    protected String sqdkglnhhwysytyfpDm;
    @XmlElement(required = true, nillable = true)
    protected String sqdkglnhhwysytyfpkpdwnsrsbh;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfpjsdkdkse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSqdkglnhhwysytyfpjsdkdkse() {
        return sqdkglnhhwysytyfpjsdkdkse;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfpjsdkdkse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSqdkglnhhwysytyfpjsdkdkse(Double value) {
        this.sqdkglnhhwysytyfpjsdkdkse = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfphm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdkglnhhwysytyfphm() {
        return sqdkglnhhwysytyfphm;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfphm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdkglnhhwysytyfphm(String value) {
        this.sqdkglnhhwysytyfphm = value;
    }

    /**
     * Gets the value of the hyfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyfpuuid() {
        return hyfpuuid;
    }

    /**
     * Sets the value of the hyfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyfpuuid(String value) {
        this.hyfpuuid = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the sqdkhyfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdkhyfpuuid() {
        return sqdkhyfpuuid;
    }

    /**
     * Sets the value of the sqdkhyfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdkhyfpuuid(String value) {
        this.sqdkhyfpuuid = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfpkpdwnsrmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdkglnhhwysytyfpkpdwnsrmc() {
        return sqdkglnhhwysytyfpkpdwnsrmc;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfpkpdwnsrmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdkglnhhwysytyfpkpdwnsrmc(String value) {
        this.sqdkglnhhwysytyfpkpdwnsrmc = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfpyfje property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSqdkglnhhwysytyfpyfje() {
        return sqdkglnhhwysytyfpyfje;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfpyfje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSqdkglnhhwysytyfpyfje(Double value) {
        this.sqdkglnhhwysytyfpyfje = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdkglnhhwysytyfpDm() {
        return sqdkglnhhwysytyfpDm;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdkglnhhwysytyfpDm(String value) {
        this.sqdkglnhhwysytyfpDm = value;
    }

    /**
     * Gets the value of the sqdkglnhhwysytyfpkpdwnsrsbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqdkglnhhwysytyfpkpdwnsrsbh() {
        return sqdkglnhhwysytyfpkpdwnsrsbh;
    }

    /**
     * Sets the value of the sqdkglnhhwysytyfpkpdwnsrsbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqdkglnhhwysytyfpkpdwnsrsbh(String value) {
        this.sqdkglnhhwysytyfpkpdwnsrsbh = value;
    }

}
