//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票印制入库信息VO
 * 
 * <p>Java class for FPYzrkxxVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPYzrkxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="yzfpmxuuid" type="{http://www.chinatax.gov.cn/dataspec/}yzfpmxuuid"/>
 *         &lt;element name="zgswskfjDm" type="{http://www.chinatax.gov.cn/dataspec/}zgswskfjDm"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="yzfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}yzfpuuid"/>
 *         &lt;element name="fpzzhm" type="{http://www.chinatax.gov.cn/dataspec/}fpzzhm"/>
 *         &lt;element name="fpkfDm" type="{http://www.chinatax.gov.cn/dataspec/}fpkfDm"/>
 *         &lt;element name="cycsmc" type="{http://www.chinatax.gov.cn/dataspec/}cycsmc"/>
 *         &lt;element name="ysdw1" type="{http://www.chinatax.gov.cn/dataspec/}ysdw1"/>
 *         &lt;element name="zfrq1" type="{http://www.chinatax.gov.cn/dataspec/}zfrq1"/>
 *         &lt;element name="gmfplqfsDm" type="{http://www.chinatax.gov.cn/dataspec/}gmfplqfsDm"/>
 *         &lt;element name="mxbfjs" type="{http://www.chinatax.gov.cn/dataspec/}mxbfjs"/>
 *         &lt;element name="xzzhm" type="{http://www.chinatax.gov.cn/dataspec/}xzzhm"/>
 *         &lt;element name="rkswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}rkswjgDm"/>
 *         &lt;element name="rkrDm" type="{http://www.chinatax.gov.cn/dataspec/}rkrDm"/>
 *         &lt;element name="cycsdjxh" type="{http://www.chinatax.gov.cn/dataspec/}cycsdjxh"/>
 *         &lt;element name="xsje" type="{http://www.chinatax.gov.cn/dataspec/}xsje"/>
 *         &lt;element name="fpqshm" type="{http://www.chinatax.gov.cn/dataspec/}fpqshm"/>
 *         &lt;element name="fs" type="{http://www.chinatax.gov.cn/dataspec/}fs"/>
 *         &lt;element name="xqshm" type="{http://www.chinatax.gov.cn/dataspec/}xqshm"/>
 *         &lt;element name="fpDm" type="{http://www.chinatax.gov.cn/dataspec/}fpDm"/>
 *         &lt;element name="wgrq" type="{http://www.chinatax.gov.cn/dataspec/}wgrq"/>
 *         &lt;element name="bz" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *         &lt;element name="dj" type="{http://www.chinatax.gov.cn/dataspec/}dj"/>
 *         &lt;element name="spr1" type="{http://www.chinatax.gov.cn/dataspec/}spr1"/>
 *         &lt;element name="kfglyDm" type="{http://www.chinatax.gov.cn/dataspec/}kfglyDm"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xs" type="{http://www.chinatax.gov.cn/dataspec/}xs"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="zfrDm" type="{http://www.chinatax.gov.cn/dataspec/}zfrDm"/>
 *         &lt;element name="wszg" type="{http://www.chinatax.gov.cn/dataspec/}wszg"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *         &lt;element name="sfytzd" type="{http://www.chinatax.gov.cn/dataspec/}sfytzd"/>
 *         &lt;element name="bfjs" type="{http://www.chinatax.gov.cn/dataspec/}bfjs"/>
 *         &lt;element name="rkrq" type="{http://www.chinatax.gov.cn/dataspec/}rkrq"/>
 *         &lt;element name="yzrkuuid" type="{http://www.chinatax.gov.cn/dataspec/}yzrkuuid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPYzrkxxVO", propOrder = {
    "sjgsdq",
    "yzfpmxuuid",
    "zgswskfjDm",
    "djxh",
    "fpzlDm",
    "yzfpuuid",
    "fpzzhm",
    "fpkfDm",
    "cycsmc",
    "ysdw1",
    "zfrq1",
    "gmfplqfsDm",
    "mxbfjs",
    "xzzhm",
    "rkswjgDm",
    "rkrDm",
    "cycsdjxh",
    "xsje",
    "fpqshm",
    "fs",
    "xqshm",
    "fpDm",
    "wgrq",
    "bz",
    "dj",
    "spr1",
    "kfglyDm",
    "lrrDm",
    "xs",
    "xgrDm",
    "zfrDm",
    "wszg",
    "zfbz1",
    "sfytzd",
    "bfjs",
    "rkrq",
    "yzrkuuid"
})
public class FPYzrkxxVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String yzfpmxuuid;
    @XmlElement(required = true, nillable = true)
    protected String zgswskfjDm;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String fpzlDm;
    @XmlElement(required = true, nillable = true)
    protected String yzfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String fpzzhm;
    @XmlElement(required = true, nillable = true)
    protected String fpkfDm;
    @XmlElement(required = true, nillable = true)
    protected String cycsmc;
    @XmlElement(required = true, nillable = true)
    protected String ysdw1;
    @XmlElement(required = true, nillable = true)
    protected String zfrq1;
    @XmlElement(required = true, nillable = true)
    protected String gmfplqfsDm;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long mxbfjs;
    @XmlElement(required = true, nillable = true)
    protected String xzzhm;
    @XmlElement(required = true, nillable = true)
    protected String rkswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String rkrDm;
    @XmlElement(required = true, nillable = true)
    protected String cycsdjxh;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double xsje;
    @XmlElement(required = true, nillable = true)
    protected String fpqshm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double fs;
    @XmlElement(required = true, nillable = true)
    protected String xqshm;
    @XmlElement(required = true, nillable = true)
    protected String fpDm;
    @XmlElement(required = true, nillable = true)
    protected String wgrq;
    @XmlElement(required = true, nillable = true)
    protected String bz;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double dj;
    @XmlElement(required = true, nillable = true)
    protected String spr1;
    @XmlElement(required = true, nillable = true)
    protected String kfglyDm;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double xs;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String zfrDm;
    @XmlElement(required = true, nillable = true)
    protected String wszg;
    @XmlElement(required = true, nillable = true)
    protected String zfbz1;
    @XmlElement(required = true, nillable = true)
    protected String sfytzd;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long bfjs;
    @XmlElement(required = true, nillable = true)
    protected String rkrq;
    @XmlElement(required = true, nillable = true)
    protected String yzrkuuid;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the yzfpmxuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYzfpmxuuid() {
        return yzfpmxuuid;
    }

    /**
     * Sets the value of the yzfpmxuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYzfpmxuuid(String value) {
        this.yzfpmxuuid = value;
    }

    /**
     * Gets the value of the zgswskfjDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZgswskfjDm() {
        return zgswskfjDm;
    }

    /**
     * Sets the value of the zgswskfjDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZgswskfjDm(String value) {
        this.zgswskfjDm = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the yzfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYzfpuuid() {
        return yzfpuuid;
    }

    /**
     * Sets the value of the yzfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYzfpuuid(String value) {
        this.yzfpuuid = value;
    }

    /**
     * Gets the value of the fpzzhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzzhm() {
        return fpzzhm;
    }

    /**
     * Sets the value of the fpzzhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzzhm(String value) {
        this.fpzzhm = value;
    }

    /**
     * Gets the value of the fpkfDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpkfDm() {
        return fpkfDm;
    }

    /**
     * Sets the value of the fpkfDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpkfDm(String value) {
        this.fpkfDm = value;
    }

    /**
     * Gets the value of the cycsmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCycsmc() {
        return cycsmc;
    }

    /**
     * Sets the value of the cycsmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCycsmc(String value) {
        this.cycsmc = value;
    }

    /**
     * Gets the value of the ysdw1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYsdw1() {
        return ysdw1;
    }

    /**
     * Sets the value of the ysdw1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYsdw1(String value) {
        this.ysdw1 = value;
    }

    /**
     * Gets the value of the zfrq1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrq1() {
        return zfrq1;
    }

    /**
     * Sets the value of the zfrq1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrq1(String value) {
        this.zfrq1 = value;
    }

    /**
     * Gets the value of the gmfplqfsDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmfplqfsDm() {
        return gmfplqfsDm;
    }

    /**
     * Sets the value of the gmfplqfsDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmfplqfsDm(String value) {
        this.gmfplqfsDm = value;
    }

    /**
     * Gets the value of the mxbfjs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMxbfjs() {
        return mxbfjs;
    }

    /**
     * Sets the value of the mxbfjs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMxbfjs(Long value) {
        this.mxbfjs = value;
    }

    /**
     * Gets the value of the xzzhm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXzzhm() {
        return xzzhm;
    }

    /**
     * Sets the value of the xzzhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXzzhm(String value) {
        this.xzzhm = value;
    }

    /**
     * Gets the value of the rkswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkswjgDm() {
        return rkswjgDm;
    }

    /**
     * Sets the value of the rkswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkswjgDm(String value) {
        this.rkswjgDm = value;
    }

    /**
     * Gets the value of the rkrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkrDm() {
        return rkrDm;
    }

    /**
     * Sets the value of the rkrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkrDm(String value) {
        this.rkrDm = value;
    }

    /**
     * Gets the value of the cycsdjxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCycsdjxh() {
        return cycsdjxh;
    }

    /**
     * Sets the value of the cycsdjxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCycsdjxh(String value) {
        this.cycsdjxh = value;
    }

    /**
     * Gets the value of the xsje property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXsje() {
        return xsje;
    }

    /**
     * Sets the value of the xsje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXsje(Double value) {
        this.xsje = value;
    }

    /**
     * Gets the value of the fpqshm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpqshm() {
        return fpqshm;
    }

    /**
     * Sets the value of the fpqshm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpqshm(String value) {
        this.fpqshm = value;
    }

    /**
     * Gets the value of the fs property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFs() {
        return fs;
    }

    /**
     * Sets the value of the fs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFs(Double value) {
        this.fs = value;
    }

    /**
     * Gets the value of the xqshm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXqshm() {
        return xqshm;
    }

    /**
     * Sets the value of the xqshm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXqshm(String value) {
        this.xqshm = value;
    }

    /**
     * Gets the value of the fpDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpDm() {
        return fpDm;
    }

    /**
     * Sets the value of the fpDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpDm(String value) {
        this.fpDm = value;
    }

    /**
     * Gets the value of the wgrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWgrq() {
        return wgrq;
    }

    /**
     * Sets the value of the wgrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWgrq(String value) {
        this.wgrq = value;
    }

    /**
     * Gets the value of the bz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBz() {
        return bz;
    }

    /**
     * Sets the value of the bz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBz(String value) {
        this.bz = value;
    }

    /**
     * Gets the value of the dj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDj() {
        return dj;
    }

    /**
     * Sets the value of the dj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDj(Double value) {
        this.dj = value;
    }

    /**
     * Gets the value of the spr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpr1() {
        return spr1;
    }

    /**
     * Sets the value of the spr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpr1(String value) {
        this.spr1 = value;
    }

    /**
     * Gets the value of the kfglyDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKfglyDm() {
        return kfglyDm;
    }

    /**
     * Sets the value of the kfglyDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKfglyDm(String value) {
        this.kfglyDm = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xs property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXs() {
        return xs;
    }

    /**
     * Sets the value of the xs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXs(Double value) {
        this.xs = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the zfrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrDm() {
        return zfrDm;
    }

    /**
     * Sets the value of the zfrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrDm(String value) {
        this.zfrDm = value;
    }

    /**
     * Gets the value of the wszg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWszg() {
        return wszg;
    }

    /**
     * Sets the value of the wszg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWszg(String value) {
        this.wszg = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

    /**
     * Gets the value of the sfytzd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSfytzd() {
        return sfytzd;
    }

    /**
     * Sets the value of the sfytzd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSfytzd(String value) {
        this.sfytzd = value;
    }

    /**
     * Gets the value of the bfjs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBfjs() {
        return bfjs;
    }

    /**
     * Sets the value of the bfjs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBfjs(Long value) {
        this.bfjs = value;
    }

    /**
     * Gets the value of the rkrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkrq() {
        return rkrq;
    }

    /**
     * Sets the value of the rkrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkrq(String value) {
        this.rkrq = value;
    }

    /**
     * Gets the value of the yzrkuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYzrkuuid() {
        return yzrkuuid;
    }

    /**
     * Sets the value of the yzrkuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYzrkuuid(String value) {
        this.yzrkuuid = value;
    }

}
