//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 发票印制验收情况VO
 * 
 * <p>Java class for FPYzysqkVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPYzysqkVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="ysrDm" type="{http://www.chinatax.gov.cn/dataspec/}ysrDm"/>
 *         &lt;element name="ysswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}ysswjgDm"/>
 *         &lt;element name="fpkfDm" type="{http://www.chinatax.gov.cn/dataspec/}fpkfDm"/>
 *         &lt;element name="yzfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}yzfpuuid"/>
 *         &lt;element name="fpyzrkbz" type="{http://www.chinatax.gov.cn/dataspec/}fpyzrkbz"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="zfrq1" type="{http://www.chinatax.gov.cn/dataspec/}zfrq1"/>
 *         &lt;element name="cycsdjxh" type="{http://www.chinatax.gov.cn/dataspec/}cycsdjxh"/>
 *         &lt;element name="rkswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}rkswjgDm"/>
 *         &lt;element name="rkrDm" type="{http://www.chinatax.gov.cn/dataspec/}rkrDm"/>
 *         &lt;element name="wgrq" type="{http://www.chinatax.gov.cn/dataspec/}wgrq"/>
 *         &lt;element name="bz" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *         &lt;element name="sfyyztzd" type="{http://www.chinatax.gov.cn/dataspec/}sfyyztzd"/>
 *         &lt;element name="ysrq" type="{http://www.chinatax.gov.cn/dataspec/}ysrq"/>
 *         &lt;element name="spr1" type="{http://www.chinatax.gov.cn/dataspec/}spr1"/>
 *         &lt;element name="kfglyDm" type="{http://www.chinatax.gov.cn/dataspec/}kfglyDm"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="zfrDm" type="{http://www.chinatax.gov.cn/dataspec/}zfrDm"/>
 *         &lt;element name="wszg" type="{http://www.chinatax.gov.cn/dataspec/}wszg"/>
 *         &lt;element name="zfbz1" type="{http://www.chinatax.gov.cn/dataspec/}zfbz1"/>
 *         &lt;element name="yzysuuid" type="{http://www.chinatax.gov.cn/dataspec/}yzysuuid"/>
 *         &lt;element name="rkrq" type="{http://www.chinatax.gov.cn/dataspec/}rkrq"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPYzysqkVO", propOrder = {
    "sjgsdq",
    "ysrDm",
    "ysswjgDm",
    "fpkfDm",
    "yzfpuuid",
    "fpyzrkbz",
    "lcslid",
    "zfrq1",
    "cycsdjxh",
    "rkswjgDm",
    "rkrDm",
    "wgrq",
    "bz",
    "sfyyztzd",
    "ysrq",
    "spr1",
    "kfglyDm",
    "lrrDm",
    "xgrDm",
    "zfrDm",
    "wszg",
    "zfbz1",
    "yzysuuid",
    "rkrq"
})
public class FPYzysqkVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String ysrDm;
    @XmlElement(required = true, nillable = true)
    protected String ysswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String fpkfDm;
    @XmlElement(required = true, nillable = true)
    protected String yzfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String fpyzrkbz;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String zfrq1;
    @XmlElement(required = true, nillable = true)
    protected String cycsdjxh;
    @XmlElement(required = true, nillable = true)
    protected String rkswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String rkrDm;
    @XmlElement(required = true, nillable = true)
    protected String wgrq;
    @XmlElement(required = true, nillable = true)
    protected String bz;
    @XmlElement(required = true, nillable = true)
    protected String sfyyztzd;
    @XmlElement(required = true, nillable = true)
    protected String ysrq;
    @XmlElement(required = true, nillable = true)
    protected String spr1;
    @XmlElement(required = true, nillable = true)
    protected String kfglyDm;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String zfrDm;
    @XmlElement(required = true, nillable = true)
    protected String wszg;
    @XmlElement(required = true, nillable = true)
    protected String zfbz1;
    @XmlElement(required = true, nillable = true)
    protected String yzysuuid;
    @XmlElement(required = true, nillable = true)
    protected String rkrq;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the ysrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYsrDm() {
        return ysrDm;
    }

    /**
     * Sets the value of the ysrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYsrDm(String value) {
        this.ysrDm = value;
    }

    /**
     * Gets the value of the ysswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYsswjgDm() {
        return ysswjgDm;
    }

    /**
     * Sets the value of the ysswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYsswjgDm(String value) {
        this.ysswjgDm = value;
    }

    /**
     * Gets the value of the fpkfDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpkfDm() {
        return fpkfDm;
    }

    /**
     * Sets the value of the fpkfDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpkfDm(String value) {
        this.fpkfDm = value;
    }

    /**
     * Gets the value of the yzfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYzfpuuid() {
        return yzfpuuid;
    }

    /**
     * Sets the value of the yzfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYzfpuuid(String value) {
        this.yzfpuuid = value;
    }

    /**
     * Gets the value of the fpyzrkbz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpyzrkbz() {
        return fpyzrkbz;
    }

    /**
     * Sets the value of the fpyzrkbz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpyzrkbz(String value) {
        this.fpyzrkbz = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the zfrq1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrq1() {
        return zfrq1;
    }

    /**
     * Sets the value of the zfrq1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrq1(String value) {
        this.zfrq1 = value;
    }

    /**
     * Gets the value of the cycsdjxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCycsdjxh() {
        return cycsdjxh;
    }

    /**
     * Sets the value of the cycsdjxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCycsdjxh(String value) {
        this.cycsdjxh = value;
    }

    /**
     * Gets the value of the rkswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkswjgDm() {
        return rkswjgDm;
    }

    /**
     * Sets the value of the rkswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkswjgDm(String value) {
        this.rkswjgDm = value;
    }

    /**
     * Gets the value of the rkrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkrDm() {
        return rkrDm;
    }

    /**
     * Sets the value of the rkrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkrDm(String value) {
        this.rkrDm = value;
    }

    /**
     * Gets the value of the wgrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWgrq() {
        return wgrq;
    }

    /**
     * Sets the value of the wgrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWgrq(String value) {
        this.wgrq = value;
    }

    /**
     * Gets the value of the bz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBz() {
        return bz;
    }

    /**
     * Sets the value of the bz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBz(String value) {
        this.bz = value;
    }

    /**
     * Gets the value of the sfyyztzd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSfyyztzd() {
        return sfyyztzd;
    }

    /**
     * Sets the value of the sfyyztzd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSfyyztzd(String value) {
        this.sfyyztzd = value;
    }

    /**
     * Gets the value of the ysrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYsrq() {
        return ysrq;
    }

    /**
     * Sets the value of the ysrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYsrq(String value) {
        this.ysrq = value;
    }

    /**
     * Gets the value of the spr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpr1() {
        return spr1;
    }

    /**
     * Sets the value of the spr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpr1(String value) {
        this.spr1 = value;
    }

    /**
     * Gets the value of the kfglyDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKfglyDm() {
        return kfglyDm;
    }

    /**
     * Sets the value of the kfglyDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKfglyDm(String value) {
        this.kfglyDm = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the zfrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfrDm() {
        return zfrDm;
    }

    /**
     * Sets the value of the zfrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfrDm(String value) {
        this.zfrDm = value;
    }

    /**
     * Gets the value of the wszg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWszg() {
        return wszg;
    }

    /**
     * Sets the value of the wszg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWszg(String value) {
        this.wszg = value;
    }

    /**
     * Gets the value of the zfbz1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZfbz1() {
        return zfbz1;
    }

    /**
     * Sets the value of the zfbz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZfbz1(String value) {
        this.zfbz1 = value;
    }

    /**
     * Gets the value of the yzysuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYzysuuid() {
        return yzysuuid;
    }

    /**
     * Sets the value of the yzysuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYzysuuid(String value) {
        this.yzysuuid = value;
    }

    /**
     * Gets the value of the rkrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkrq() {
        return rkrq;
    }

    /**
     * Sets the value of the rkrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkrq(String value) {
        this.rkrq = value;
    }

}
