//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 调查巡查整合表VO
 * 
 * <p>Java class for FPDcxczhbVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPDcxczhbVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="dcxczhuuid" type="{http://www.chinatax.gov.cn/dataspec/}dcxczhuuid"/>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="zhrq" type="{http://www.chinatax.gov.cn/dataspec/}zhrq"/>
 *         &lt;element name="lsrwbh" type="{http://www.chinatax.gov.cn/dataspec/}lsrwbh"/>
 *         &lt;element name="pfbz" type="{http://www.chinatax.gov.cn/dataspec/}pfbz"/>
 *         &lt;element name="zhrwbh" type="{http://www.chinatax.gov.cn/dataspec/}zhrwbh"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="zhswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}zhswjgDm"/>
 *         &lt;element name="zhrDm" type="{http://www.chinatax.gov.cn/dataspec/}zhrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPDcxczhbVO", propOrder = {
    "djxh",
    "dcxczhuuid",
    "sjgsdq",
    "zhrq",
    "lsrwbh",
    "pfbz",
    "zhrwbh",
    "lrrDm",
    "xgrDm",
    "zhswjgDm",
    "zhrDm"
})
public class FPDcxczhbVO {

    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String dcxczhuuid;
    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String zhrq;
    @XmlElement(required = true, nillable = true)
    protected String lsrwbh;
    @XmlElement(required = true, nillable = true)
    protected String pfbz;
    @XmlElement(required = true, nillable = true)
    protected String zhrwbh;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String zhswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String zhrDm;

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the dcxczhuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDcxczhuuid() {
        return dcxczhuuid;
    }

    /**
     * Sets the value of the dcxczhuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDcxczhuuid(String value) {
        this.dcxczhuuid = value;
    }

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the zhrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZhrq() {
        return zhrq;
    }

    /**
     * Sets the value of the zhrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZhrq(String value) {
        this.zhrq = value;
    }

    /**
     * Gets the value of the lsrwbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLsrwbh() {
        return lsrwbh;
    }

    /**
     * Sets the value of the lsrwbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLsrwbh(String value) {
        this.lsrwbh = value;
    }

    /**
     * Gets the value of the pfbz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfbz() {
        return pfbz;
    }

    /**
     * Sets the value of the pfbz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfbz(String value) {
        this.pfbz = value;
    }

    /**
     * Gets the value of the zhrwbh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZhrwbh() {
        return zhrwbh;
    }

    /**
     * Sets the value of the zhrwbh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZhrwbh(String value) {
        this.zhrwbh = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the zhswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZhswjgDm() {
        return zhswjgDm;
    }

    /**
     * Sets the value of the zhswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZhswjgDm(String value) {
        this.zhswjgDm = value;
    }

    /**
     * Gets the value of the zhrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZhrDm() {
        return zhrDm;
    }

    /**
     * Sets the value of the zhrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZhrDm(String value) {
        this.zhrDm = value;
    }

}
