//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 已认证增值税扣税凭证清单海关缴款书VO
 * 
 * <p>Java class for FPYrzzzskspzqdHgjksVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPYrzzzskspzqdHgjksVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="sqdkhgjkzzszyjksskjexj" type="{http://www.chinatax.gov.cn/dataspec/}sqdkhgjkzzszyjksskjexj"/>
 *         &lt;element name="ydkhgjkzzszyjksskjexj" type="{http://www.chinatax.gov.cn/dataspec/}ydkhgjkzzszyjksskjexj"/>
 *         &lt;element name="hgjksuuid" type="{http://www.chinatax.gov.cn/dataspec/}hgjksuuid"/>
 *         &lt;element name="ydkhgjkzzszyjksfs" type="{http://www.chinatax.gov.cn/dataspec/}ydkhgjkzzszyjksfs"/>
 *         &lt;element name="ycjhgjkzzszyjksfszj" type="{http://www.chinatax.gov.cn/dataspec/}ycjhgjkzzszyjksfszj"/>
 *         &lt;element name="cjrDm" type="{http://www.chinatax.gov.cn/dataspec/}cjrDm"/>
 *         &lt;element name="waqsbdkzzskspzdksqduuid" type="{http://www.chinatax.gov.cn/dataspec/}waqsbdkzzskspzdksqduuid"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="ycjhgjkzzszyjksskjezj" type="{http://www.chinatax.gov.cn/dataspec/}ycjhgjkzzszyjksskjezj"/>
 *         &lt;element name="cjswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}cjswjgDm"/>
 *         &lt;element name="tbsj" type="{http://www.chinatax.gov.cn/dataspec/}tbsj"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="sqdkhgjkzzszyjksfs" type="{http://www.chinatax.gov.cn/dataspec/}sqdkhgjkzzszyjksfs"/>
 *         &lt;element name="ssny" type="{http://www.chinatax.gov.cn/dataspec/}ssny"/>
 *         &lt;element name="zzskspzlxDm" type="{http://www.chinatax.gov.cn/dataspec/}zzskspzlxDm"/>
 *         &lt;element name="cjrq1" type="{http://www.chinatax.gov.cn/dataspec/}cjrq1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPYrzzzskspzqdHgjksVO", propOrder = {
    "sjgsdq",
    "sqdkhgjkzzszyjksskjexj",
    "ydkhgjkzzszyjksskjexj",
    "hgjksuuid",
    "ydkhgjkzzszyjksfs",
    "ycjhgjkzzszyjksfszj",
    "cjrDm",
    "waqsbdkzzskspzdksqduuid",
    "lrrDm",
    "ycjhgjkzzszyjksskjezj",
    "cjswjgDm",
    "tbsj",
    "xgrDm",
    "sqdkhgjkzzszyjksfs",
    "ssny",
    "zzskspzlxDm",
    "cjrq1"
})
public class FPYrzzzskspzqdHgjksVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double sqdkhgjkzzszyjksskjexj;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ydkhgjkzzszyjksskjexj;
    @XmlElement(required = true, nillable = true)
    protected String hgjksuuid;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long ydkhgjkzzszyjksfs;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long ycjhgjkzzszyjksfszj;
    @XmlElement(required = true, nillable = true)
    protected String cjrDm;
    @XmlElement(required = true, nillable = true)
    protected String waqsbdkzzskspzdksqduuid;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ycjhgjkzzszyjksskjezj;
    @XmlElement(required = true, nillable = true)
    protected String cjswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String tbsj;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long sqdkhgjkzzszyjksfs;
    @XmlElement(required = true, nillable = true)
    protected String ssny;
    @XmlElement(required = true, nillable = true)
    protected String zzskspzlxDm;
    @XmlElement(required = true, nillable = true)
    protected String cjrq1;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the sqdkhgjkzzszyjksskjexj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSqdkhgjkzzszyjksskjexj() {
        return sqdkhgjkzzszyjksskjexj;
    }

    /**
     * Sets the value of the sqdkhgjkzzszyjksskjexj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSqdkhgjkzzszyjksskjexj(Double value) {
        this.sqdkhgjkzzszyjksskjexj = value;
    }

    /**
     * Gets the value of the ydkhgjkzzszyjksskjexj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYdkhgjkzzszyjksskjexj() {
        return ydkhgjkzzszyjksskjexj;
    }

    /**
     * Sets the value of the ydkhgjkzzszyjksskjexj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYdkhgjkzzszyjksskjexj(Double value) {
        this.ydkhgjkzzszyjksskjexj = value;
    }

    /**
     * Gets the value of the hgjksuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHgjksuuid() {
        return hgjksuuid;
    }

    /**
     * Sets the value of the hgjksuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHgjksuuid(String value) {
        this.hgjksuuid = value;
    }

    /**
     * Gets the value of the ydkhgjkzzszyjksfs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getYdkhgjkzzszyjksfs() {
        return ydkhgjkzzszyjksfs;
    }

    /**
     * Sets the value of the ydkhgjkzzszyjksfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setYdkhgjkzzszyjksfs(Long value) {
        this.ydkhgjkzzszyjksfs = value;
    }

    /**
     * Gets the value of the ycjhgjkzzszyjksfszj property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getYcjhgjkzzszyjksfszj() {
        return ycjhgjkzzszyjksfszj;
    }

    /**
     * Sets the value of the ycjhgjkzzszyjksfszj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setYcjhgjkzzszyjksfszj(Long value) {
        this.ycjhgjkzzszyjksfszj = value;
    }

    /**
     * Gets the value of the cjrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCjrDm() {
        return cjrDm;
    }

    /**
     * Sets the value of the cjrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCjrDm(String value) {
        this.cjrDm = value;
    }

    /**
     * Gets the value of the waqsbdkzzskspzdksqduuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaqsbdkzzskspzdksqduuid() {
        return waqsbdkzzskspzdksqduuid;
    }

    /**
     * Sets the value of the waqsbdkzzskspzdksqduuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaqsbdkzzskspzdksqduuid(String value) {
        this.waqsbdkzzskspzdksqduuid = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the ycjhgjkzzszyjksskjezj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYcjhgjkzzszyjksskjezj() {
        return ycjhgjkzzszyjksskjezj;
    }

    /**
     * Sets the value of the ycjhgjkzzszyjksskjezj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYcjhgjkzzszyjksskjezj(Double value) {
        this.ycjhgjkzzszyjksskjezj = value;
    }

    /**
     * Gets the value of the cjswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCjswjgDm() {
        return cjswjgDm;
    }

    /**
     * Sets the value of the cjswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCjswjgDm(String value) {
        this.cjswjgDm = value;
    }

    /**
     * Gets the value of the tbsj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbsj() {
        return tbsj;
    }

    /**
     * Sets the value of the tbsj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbsj(String value) {
        this.tbsj = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the sqdkhgjkzzszyjksfs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSqdkhgjkzzszyjksfs() {
        return sqdkhgjkzzszyjksfs;
    }

    /**
     * Sets the value of the sqdkhgjkzzszyjksfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSqdkhgjkzzszyjksfs(Long value) {
        this.sqdkhgjkzzszyjksfs = value;
    }

    /**
     * Gets the value of the ssny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsny() {
        return ssny;
    }

    /**
     * Sets the value of the ssny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsny(String value) {
        this.ssny = value;
    }

    /**
     * Gets the value of the zzskspzlxDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZzskspzlxDm() {
        return zzskspzlxDm;
    }

    /**
     * Sets the value of the zzskspzlxDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZzskspzlxDm(String value) {
        this.zzskspzlxDm = value;
    }

    /**
     * Gets the value of the cjrq1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCjrq1() {
        return cjrq1;
    }

    /**
     * Sets the value of the cjrq1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCjrq1(String value) {
        this.cjrq1 = value;
    }

}
