//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 货物运输业增值税专用发票运输信息VO
 * 
 * <p>Java class for FPDkHwyszzsfpYsxxVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPDkHwyszzsfpYsxxVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="jshj" type="{http://www.chinatax.gov.cn/dataspec/}jshj"/>
 *         &lt;element name="cbdw" type="{http://www.chinatax.gov.cn/dataspec/}cbdw"/>
 *         &lt;element name="ddd" type="{http://www.chinatax.gov.cn/dataspec/}ddd"/>
 *         &lt;element name="hwysfpuuid" type="{http://www.chinatax.gov.cn/dataspec/}hwysfpuuid"/>
 *         &lt;element name="bz" type="{http://www.chinatax.gov.cn/dataspec/}bz"/>
 *         &lt;element name="jyd" type="{http://www.chinatax.gov.cn/dataspec/}jyd"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="jehj" type="{http://www.chinatax.gov.cn/dataspec/}jehj"/>
 *         &lt;element name="hwysfpysxxuuid" type="{http://www.chinatax.gov.cn/dataspec/}hwysfpysxxuuid"/>
 *         &lt;element name="yshwxx" type="{http://www.chinatax.gov.cn/dataspec/}yshwxx"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *         &lt;element name="qyd" type="{http://www.chinatax.gov.cn/dataspec/}qyd"/>
 *         &lt;element name="ccdwhj" type="{http://www.chinatax.gov.cn/dataspec/}ccdwhj"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPDkHwyszzsfpYsxxVO", propOrder = {
    "sjgsdq",
    "jshj",
    "cbdw",
    "ddd",
    "hwysfpuuid",
    "bz",
    "jyd",
    "lrrDm",
    "jehj",
    "hwysfpysxxuuid",
    "yshwxx",
    "xgrDm",
    "qyd",
    "ccdwhj"
})
public class FPDkHwyszzsfpYsxxVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double jshj;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double cbdw;
    @XmlElement(required = true, nillable = true)
    protected String ddd;
    @XmlElement(required = true, nillable = true)
    protected String hwysfpuuid;
    @XmlElement(required = true, nillable = true)
    protected String bz;
    @XmlElement(required = true, nillable = true)
    protected String jyd;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double jehj;
    @XmlElement(required = true, nillable = true)
    protected String hwysfpysxxuuid;
    @XmlElement(required = true, nillable = true)
    protected String yshwxx;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;
    @XmlElement(required = true, nillable = true)
    protected String qyd;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double ccdwhj;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the jshj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJshj() {
        return jshj;
    }

    /**
     * Sets the value of the jshj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJshj(Double value) {
        this.jshj = value;
    }

    /**
     * Gets the value of the cbdw property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCbdw() {
        return cbdw;
    }

    /**
     * Sets the value of the cbdw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCbdw(Double value) {
        this.cbdw = value;
    }

    /**
     * Gets the value of the ddd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDdd() {
        return ddd;
    }

    /**
     * Sets the value of the ddd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDdd(String value) {
        this.ddd = value;
    }

    /**
     * Gets the value of the hwysfpuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHwysfpuuid() {
        return hwysfpuuid;
    }

    /**
     * Sets the value of the hwysfpuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHwysfpuuid(String value) {
        this.hwysfpuuid = value;
    }

    /**
     * Gets the value of the bz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBz() {
        return bz;
    }

    /**
     * Sets the value of the bz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBz(String value) {
        this.bz = value;
    }

    /**
     * Gets the value of the jyd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJyd() {
        return jyd;
    }

    /**
     * Sets the value of the jyd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJyd(String value) {
        this.jyd = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the jehj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJehj() {
        return jehj;
    }

    /**
     * Sets the value of the jehj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJehj(Double value) {
        this.jehj = value;
    }

    /**
     * Gets the value of the hwysfpysxxuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHwysfpysxxuuid() {
        return hwysfpysxxuuid;
    }

    /**
     * Sets the value of the hwysfpysxxuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHwysfpysxxuuid(String value) {
        this.hwysfpysxxuuid = value;
    }

    /**
     * Gets the value of the yshwxx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYshwxx() {
        return yshwxx;
    }

    /**
     * Sets the value of the yshwxx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYshwxx(String value) {
        this.yshwxx = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

    /**
     * Gets the value of the qyd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQyd() {
        return qyd;
    }

    /**
     * Sets the value of the qyd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQyd(String value) {
        this.qyd = value;
    }

    /**
     * Gets the value of the ccdwhj property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCcdwhj() {
        return ccdwhj;
    }

    /**
     * Sets the value of the ccdwhj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCcdwhj(Double value) {
        this.ccdwhj = value;
    }

}
