//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 03:50:11 下午 CST 
//


package cn.gov.chinatax.hxzg.fp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务机关期初库存采集VO
 * 
 * <p>Java class for FPSwjgqckccjVOEx complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwjgqckccjVOEx">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}FPSwjgqckccjVO">
 *       &lt;sequence>
 *         &lt;element name="mbfs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fpdmmc" type="{http://www.chinatax.gov.cn/dataspec/}fpdmmc"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwjgqckccjVOEx", propOrder = {
    "mbfs",
    "fpdmmc"
})
public class FPSwjgqckccjVOEx
    extends FPSwjgqckccjVO
{

    @XmlElement(required = true)
    protected String mbfs;
    @XmlElement(required = true)
    protected String fpdmmc;

    /**
     * Gets the value of the mbfs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbfs() {
        return mbfs;
    }

    /**
     * Sets the value of the mbfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbfs(String value) {
        this.mbfs = value;
    }

    /**
     * Gets the value of the fpdmmc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpdmmc() {
        return fpdmmc;
    }

    /**
     * Sets the value of the fpdmmc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpdmmc(String value) {
        this.fpdmmc = value;
    }

}
